### ISSUE TITLE
demo_network.c中遇见的一些问题

### ISSUE THREAD

**Issue by mymx** [Ai-Thinker-Open/GPRS_C_SDK#100]
## 1. SDK version（SDK 版本）

{

V1505

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

我在学习初步的代码，之前没接触过。请问：void OnNetworkStatusChanged(Network_Status_t status)
中的status事件是如何触发的？需要发送AT指令才能触发嘛？

}

---

**Comment by mymx** [comment]
补充：在socket例程中，自动注册成功之后，继而开始的Network_StartAttach（）是不是就是完成了

AT+CGATT=1的指令集发送操作？

**Comment by Neutree** [comment]
片上开发和AT开发是分开的，C SDK里面不包含AT指令部分，但是实现的功能是一样的，`Network_StartAttach`实现的功能确实跟`AT+CGATT=1`是一样的
