### ISSUE TITLE
ds18b20 读温度，值有跳变，怀疑是任务（进程切换造成的时序问题），如何解决cpu切换的问题（实现原子操作，保证时序）,进入时序时已挂起所能挂起的task？

### ISSUE THREAD

**Issue by SISYFirst** [Ai-Thinker-Open/GPRS_C_SDK#103]
## 1. SDK version（SDK 版本）

{
latest

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
ds18b20,总能观察到跳变

}

---

**Comment by fugreat** [comment]
有个小建议：单纯想采温度的话，换个i2c接口的温度传感器就好了

**Comment by Neutree** [comment]
https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/include/api_sys.h 也可以试试这两个函数
