### ISSUE TITLE
引脚分配的文件在哪？我需要引脚分配

### ISSUE THREAD

**Issue by mymx** [Ai-Thinker-Open/GPRS_C_SDK#104]
## 1. SDK version（SDK 版本）

{

V1506

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

引脚定义在哪啊，翻遍了所有的文件，就是没见到引脚相关的叙述

}

---

**Comment by Neutree** [comment]
https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/zh/ying-jian/kai-fa-ban-pudding.html
