### ISSUE TITLE
stdlib.h functions not working [need help]

### ISSUE THREAD

**Issue by punee995** [Ai-Thinker-Open/GPRS_C_SDK#106]
## 1. SDK version（SDK 版本）

{

V1.506

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

```
        double val;
        char str[20];
        strcpy(str, "9.8993489");
        val = atof(str);
        uint8_t buff[50];
        sprintf(buff,"%d.%d",(int)val,abs((int)(val*100)%100));
        Trace(1,"%s",buff);
```
anyone know how to decode **nmea to decimal** it's pain in @$$ 

**@Neutree when new update will be available??**
}

---

**Comment by Neutree** [comment]
resolved:https://github.com/Ai-Thinker-Open/GPRS_C_SDK/releases
