### ISSUE TITLE
gcvt() not working

### ISSUE THREAD

**Issue by punee995** [Ai-Thinker-Open/GPRS_C_SDK#107]
## 1. SDK version（SDK 版本）

{

**V1.506**

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
```
        #include "stdlib.h"

        double value = 1.234567;
        char bufff[20];
        gcvt(value, 3, bufff);
        Trace(1,"%s",bufff);
```
@Neutree please resolve it ASAP!
can't able to convert float to char{see below image}.

 
![image](https://user-images.githubusercontent.com/7541915/38498148-1ab9399c-3c21-11e8-84e3-4c32c1d0e46a.png)

}

---

**Comment by Neutree** [comment]
see v2.1.1
