### ISSUE TITLE
SDK环境搭建

### ISSUE THREAD

**Issue by Davide3Cao** [Ai-Thinker-Open/GPRS_C_SDK#109]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
用cd命令进到gprs_c_sdk下面，但是用work gprs_c_sdk时就提示
work: command not found

}

---

**Comment by vencol** [comment]
work 指令是在家目录先的.bashrc里面定义的

**Comment by vencol** [comment]
work是在家目录里面的.bashrc里面定义的，只是为了方便到你的工程目录
alias  work='source $HOME/cygenv.sh'
具体的设置你要修改你自己的cygenv.sh

**Comment by Davide3Cao** [comment]
按bilibili视频里的修改了相应了的文件，是不是还会有一些情况导致运行不了work和build命令

**Comment by Neutree** [comment]
新的CSDTK4.2已经更新，使用更简单，参考 [安装文档](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/zh/c-sdk/kai-fa-huan-jing-an-zhuang.html)
