### ISSUE TITLE
Getting started with A9G bds development board 

### ISSUE THREAD

**Issue by ShahzadHamid** [Ai-Thinker-Open/GPRS_C_SDK#112]
Hi I am Shahzad and wanted to know how to get started a9g board?
I recently purchased an a9g bds development board but I am confused how to start it?
Please ans my questions; what is this module? how to program it? what is the programming language?   
can i program it using arduino ide?

waiting for you reply 
thanks in advance

**Comment by vencol** [comment]
maybe you should have a look on readme first
https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/README_EN.md

**Comment by Neutree** [comment]
https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/

**Comment by jumpjack** [comment]
I can't event boot it up: if I connect to PC using USB, two blue LEDs shortly blink, then nothing.
No new serial port detected.
I read that it should just start as soon as I connect USB, isnt't this correct?
