### ISSUE TITLE
sdk为何没有基站定位的相关代码，不支持吗

### ISSUE THREAD

**Issue by wslmcu** [Ai-Thinker-Open/GPRS_C_SDK#113]
sdk为何没有基站定位的相关代码，不支持吗

**Comment by punee995** [comment]
For Base station positioning you'll need MCC, MNC, LAC and CellID(CID). and there is demo for it in [network2](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/tree/master/demo/network2).

**Comment by Neutree** [comment]
基站定位参考 network2，可以获得基站信息，根据这些信息即可做基站定位
