### ISSUE TITLE
udp无法通信

### ISSUE THREAD

**Issue by SISYFirst** [Ai-Thinker-Open/GPRS_C_SDK#115]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？
{
什么样的步骤，都稳定出现，希望早点解决

}

---

**Comment by Neutree** [comment]
已经修复，2.1版本及之后版本
