### ISSUE TITLE
死机

### ISSUE THREAD

**Issue by Harlan-pan** [Ai-Thinker-Open/GPRS_C_SDK#116]
## 1. SDK version（SDK 版本）

{
GPRS_C_SDK_dev

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
1.A9G,demo板，安信可淘宝购买。
2.稳定上传数据5天，昨天断开了，用coolwatcher查看，没有任何数据输出(包括A9本身调试数据)，不知道A9现在处于什么样一种状态，该如何判断。按复位键后，正常运行，正常数据输出。如果用A9来做主控，这个问题就大了。

}

---

**Comment by Neutree** [comment]
* 可以开着调试工具拷机找到复现问题的方法
* 或者直接编译release版本，在死机后自动重启，编译release版本的方法是在编译命令后加一个release参数，比如 `build.bat demo gpio release`
