### ISSUE TITLE
如何获取实时时间呢？

### ISSUE THREAD

**Issue by niguang1** [Ai-Thinker-Open/GPRS_C_SDK#117]
函数TIME_GetRtcTIme无法使用，定义RTC_Time_t类型的结构体之后提示storage size of 'time' isn't known（time就是定义的那个结构体）。
然后百度来的C语言将Unix时间戳转化为实时时间的代码，链接如下：https://www.cnblogs.com/craigtao/p/3973056.html
转化来的时间不正确。不知道咋办了。

**Comment by Neutree** [comment]
可能是哪里使用错误了，
* 参考例程：[demo/time](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/time/src/demo_time.c)
* 文档：[time](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/zh/c-sdk/gong-neng-ji-api/timertc.html)
