### ISSUE TITLE
$PROJ_WORKDIR/soft 这个目录从哪来的？

### ISSUE THREAD

**Issue by songwanqian** [Ai-Thinker-Open/GPRS_C_SDK#118]
## 1. SDK version（SDK 版本）

GPRS_C_SDK_V1505

---

## 2. 编译器版本：

CSDTK4.1

---

编译器脚本里的 work 命令里：
```
export PROJ=$1
export PROJ_WORKDIR=$PROJ_ROOT/$PROJ
export SOFT_WORKDIR=$PROJ_WORKDIR/soft
if test -f $SOFT_WORKDIR/env/set_env.sh; then
    source $SOFT_WORKDIR/env/set_env.sh
fi
if cd $SOFT_WORKDIR; then
    echo "Project Switched to $PROJ"
else
    echo "Failed to switch project to $PROJ"
fi
```
这个soft目录是干嘛的？SDK里没有啊

**Comment by Neutree** [comment]
这个自己修改就好了

**Comment by Neutree** [comment]
编译器版本已经更新到[4.2](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/zh/c-sdk/kai-fa-huan-jing-an-zhuang.html), 为了在windows下更好地集成, 不再使用cygwin了,安装和编译使用起来更加方便
