### ISSUE TITLE
CSDTK4.2 对应SDK和教程不一致

### ISSUE THREAD

**Issue by ndtcenter** [Ai-Thinker-Open/GPRS_C_SDK#120]
## 1. SDK version（SDK 版本）

{
1、GPRS_C_SDK 1.506对应的国内链接还是1.505；
2、1.505的文件夹中不存在隐藏的文件夹 .git

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

}

---

**Comment by Neutree** [comment]
* 已经更新了[对应CSDTK4.2版本的SDK](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/releases), 虽然之前的3.8版本也还是可以编译的,之后在windows上就尽量不用cygwin了,太不方便了
* .git文件夹在发布版本是不存在的,只有自己用git克隆才会有这个文件夹
