### ISSUE TITLE
A9g board programming 

### ISSUE THREAD

**Issue by ShahzadHamid** [Ai-Thinker-Open/GPRS_C_SDK#122]
Please someone guide me can I programme my a9g board with Arduino IDE software?  I am much confused about that how to program my module. Please help I am new on this module. 
Thanks in Advance

**Comment by capantoja** [comment]
I understand that the programming from the arduino ide is not yet supported, to program the module an app called coolwatcher is used and the pins HST_TX and HST_RX are used through a USB - Serial converter, to see the complete procedure follow the instructions of the video
https://www.bilibili.com/video/av16579395/

**Comment by Neutree** [comment]
* documentation [here](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/), and 'how to intall' [here](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/installation.html)
* no arduino IDE support, download firmware with coolwatcher(RDA provided)

**Comment by jumpjack** [comment]
news about IDE support?

**Comment by jumpjack** [comment]
up!

**Comment by majidmp97** [comment]
**is possible program a9g directly without microcontroller?**
