### ISSUE TITLE
CSDTK Link is bad

### ISSUE THREAD

**Issue by Obaid-ur-Rehman** [Ai-Thinker-Open/GPRS_C_SDK#128]
Please share a working CSDTK Link.

## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

}

---

**Comment by Neutree** [comment]
csdtk4.2    https://pan.baidu.com/s/1Oa5tvWW2Flfl5UJITk980g

**Comment by Obaid-ur-Rehman** [comment]
Error 404 is showing.
Please share an alternative link.
Regards

**Comment by Neutree** [comment]
dropbox: https://www.dropbox.com/s/mvyyo4rp5lossms/CSDTK42.7z?dl=0
direct link:  http://test.ai-thinker.com/csdk/CSDTK42.7z
baidu cloud: https://pan.baidu.com/s/1Oa5tvWW2Flfl5UJITk980g

**Comment by bkrajendra** [comment]
All of these links are not working.
Does anyone have the proper link to CSDTK42?

**Comment by ahammers** [comment]
Dropbox-Link seems to work. At least it is downloading a 209 MiB file.

Try https://www.dropbox.com/s/mvyyo4rp5lossms/CSDTK42.7z

However, I had to download it twice. First download showed error while unpacking.

**Comment by Neutree** [comment]
mega: https://mega.nz/folder/WiZlDSJZ#ftSjd5U5vRBolHCyd_hE3A

百度云:  https://pan.baidu.com/s/1uF0G9p-W9KrrxD-dFCJ7Og      密钥: jtvu

**Comment by ahammers** [comment]
Thank you very much for the new version 👍. With this archive (from 2020-12-16 post) I was able to build the gps_tracker example without any problem on my Windows 10.
