### ISSUE TITLE
固件无法下载

### ISSUE THREAD

**Issue by MasterSU** [Ai-Thinker-Open/GPRS_C_SDK#131]
## 1. SDK version（SDK 版本）

{

4.2

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

在使用coolwatcher下载时，会出现：“`CHST_Read32': Request to coolhost timed out ! (CoolHostTimeoutError)”这个错误，我对应错误解决方法，按下复位后立即点击下载同样无法下载成功，我保证串口是连通的。原始固件没有动过

}

---

**Comment by Neutree** [comment]
应该是哪里没设置好，得仔细排查咯

可以先用升级固件的方法升级一下固件，看能不能下载，再来用coolwatcher尝试
http://wiki.ai-thinker.com/gprs_download

**Comment by CallaDai** [comment]
> 应该是哪里没设置好，得仔细排查咯
> 
> 可以先用升级固件的方法升级一下固件，看能不能下载，再来用coolwatcher尝试
> http://wiki.ai-thinker.com/gprs_download

我打开固件升级，点击Start，完全没有反应啊
