### ISSUE TITLE
FOTA Not working.

### ISSUE THREAD

**Issue by punee995** [Ai-Thinker-Open/GPRS_C_SDK#133]
## 1. SDK version（SDK 版本）

{

V2.100

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

demo FOTA not working.
no changes have been made. 

![capture](https://user-images.githubusercontent.com/7541915/40616454-b9e8ffcc-62a8-11e8-9f61-6646b4dba20f.PNG)

}

---

**Comment by Neutree** [comment]
you tried it with wrong way, please refer to [fota doc](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/function-api/fota.html)

**Comment by punee995** [comment]
yup!
