### ISSUE TITLE
V2101 第2次调用GPS_Open()后会死机

### ISSUE THREAD

**Issue by chenfuvip** [Ai-Thinker-Open/GPRS_C_SDK#139]
1、GPS_Open()
2、一段时间后GPS_Close()
3、一段时间后GPS_Open()，就会死机重启，调试信息如下：
ASSERT DETAIL : 
Uart already open

**Comment by Neutree** [comment]
应该是GPS_Close()没关闭串口，下个版本修复

**Comment by Neutree** [comment]
在master分支已经修复
