### ISSUE TITLE
Unable to download any on pundit a9g

### ISSUE THREAD

**Issue by bitwarriors** [Ai-Thinker-Open/GPRS_C_SDK#140]
Goodmorning,
after some little problems on making the lod files, now (around 2 weeks) I'm not able to download the new firmware. My coolwatcher (2.00.02) stops on this error, after a workig first connection: 

`CHST_Read32': Request to coolhost timed out ! (CoolHostTimeoutError)

./rbbase/common/coolhost_connections.rb 161 `CHST_Read32'
./rbbase/common/coolhost_connections.rb 161 `read32'
./rbbase/common/base.rb  85   `read'
./rbbase/common/base.rb  239  `read'
./chipgen/Modem2G/toolpool/scripts/8809/target_executor.rb 72  `enterHostMonitor'
./chipgen/Modem2G/toolpool/scripts/ChipStd/target_executor.rb  366  `session'
./chipgen/Modem2G/toolpool/scripts/ChipStd/ramrun.rb  12  `doramrunXfer'
./chipgen/Modem2G/toolpool/scripts/ChipStd/ramrun.rb  62  `ramrunXfer'
./chipgen/Modem2G/toolpool/plugins/fastpf/fastpf.rb   212 `dofastpfXfer'
./chipgen/Modem2G/toolpool/plugins/fastpf/fastpf.rb   718 `dofastpf'
./chipgen/Modem2G/toolpool/plugins/fastpf/fastpf.rb   788 `fastpf'
./chipgen/Modem2G/toolpool/plugins/fastpf/fastpfplugin.rb  83  `fastpfGenericGo'
./chipgen/Modem2G/toolpool/plugins/fastpf/fastpfplugin.rb  112  `fastpfGo'

the CSDK is the 4.2 and the GPRS_SDK is the latest on line, the usb-uart is the cp2102 and the tx->hst-rx and rx->hst-tx pins are connected.
I'm very frustrated because no way to get rid of this error.
Any helps will be gratefully accepted 👍 
Thank you

**Comment by Neutree** [comment]
refer to here:https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/burn-debug.html#coolwatcher-download-fail

**Comment by bitwarriors** [comment]
Thank you Neutree for your quick reply, unfortunately before posting my request I've already followed the hints on that place :-( . I don't understand if is a device problem or a connection problem. When I fire-up the coolhost application do I have to read more than the only Open Com4 etc etc ?
Thank You again

**Comment by lamqhoang** [comment]
Hi @bitwarriors ,
Make sure you have the good wiring, I had the same issue with a long jumper wire before. Even if you have connected the USB-UART and the A9G board to the same computer, it is recommended to have a jumper wire for GND.

**Comment by Neutree** [comment]
you can try [AT firmware upgrade tool](http://wiki.ai-thinker.com/_media/ai-thinker_gsm_module_download_tool_v11.00.04.7z) first, and [AT firmware here](http://wiki.ai-thinker.com/_media/gprs/a9g-v02.01.20180416rc.zip),
![image](https://user-images.githubusercontent.com/8625829/41388396-5172b348-6fbe-11e8-8149-0f08037b449e.png),  uart COM port(s) will appear if hardware connection is ok,

**Comment by bitwarriors** [comment]
Thanks all my friends,
sadly i can't test because I'm not in my place, buut as soon as I get home I 'll check !
I will keep you informed on my progresses :-))

**Comment by bitwarriors** [comment]
Hi all!
I tried all the solutions you told me and seems there is a problem about the connection, means the usb uart cp2102 is connected and I have the evidence in the hardware list 
<img width="368" alt="evidencesilab" src="https://user-images.githubusercontent.com/25318722/42241053-918b4f8a-7f09-11e8-84c2-27718d55051e.png">
but when i open any of the sever tool the result is I can't use the device 
<img width="692" alt="evidencesilab2" src="https://user-images.githubusercontent.com/25318722/42241117-c1561b5a-7f09-11e8-8601-698cba324856.png">

AAARGH!

**Comment by bitwarriors** [comment]
Ok ... Miracle! I don't know why but now all is working !
I uploaded a demo / gps ... but now, how can i monitor if the gps is working trhough a terminal, like arduino method?
thank you all

**Comment by dhernandezl** [comment]
Did you manage to solve permanently?
I have the same problem

**Comment by bitwarriors** [comment]
Hi … not permanently … infact I don’t understand where is the real problem … can we submit again tighter the request ?

**Comment by tadeastehan** [comment]
Did you find any solution?

**Comment by bitwarriors** [comment]
Not yet

**Comment by tadeastehan** [comment]
Is this good in  coolwatcher?
![image](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/assets/110731911/a91f6779-3f9e-4fe2-a7ec-d72aab68761b)
But when I try to launch fastpf then I get this familiar error :D
![image](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/assets/110731911/c63032e6-294b-4a2c-ace9-9aa027ca3512)
I use this CP2102 TTL convertor: https://www.laskakit.cz/prevodnik-6pin-usb-ttl-uart--cp2102--dtr-pin/
Do you think it's the TTL converter's fault?

**Comment by collins-kariuki** [comment]
@tadeastehan any breakthrough on this?

**Comment by tadeastehan** [comment]
No, I gave up trying to get it to work.

**Comment by collins-kariuki** [comment]
Alright.
I'm still digging around.
Thanks for the prompt response.

**Comment by tadeastehan** [comment]
If you find the solution to this problem, let me know.

**Comment by MCPM23** [comment]
![SharedScreenshot](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/assets/122202218/62ee99ae-9d55-420e-8a34-4a7e6586e82f)
I fixed it by setting the port beforehand in this window. The problem now, after flasing it, it's that the module doesn't turn on :( so I'm having again this issue

**Comment by BSPATELSB** [comment]
Hello Have resolved this problem, by applying below steps...

-> First verify the GND connection, If you give the power from USB micro cable then do not connect GND wire
-> after this validation, restart coolwatcher application 
-> Verify your COM port carefully
-> Then after COM port connection confirmation, flash both .lod files
-> You should find that, the flash error has resolved

**Comment by 26mrlon** [comment]
`CHST_Read32': Request to coolhost timed out! (CoolHostTimeoutError)

Hello, guys! I found a solution to this error because I encountered it too. It took me almost two days to figure it out, but I finally solved it today.

First, you need to connect the RX pin to the HST_TX and the TX pin to the HST_RX.

Next, take your micro USB cable, connect it to your computer, and then to your A9G board. This means the power is coming from the micro USB.

Before opening CoolWatcher, press the PWR button on the A9G board.

Then, flash the two LOD files.
