### ISSUE TITLE
GPS GIVING 4 LONGITUDE AND LATTITUDE IN 4 DIGITS

### ISSUE THREAD

**Issue by fewtechiot** [Ai-Thinker-Open/GPRS_C_SDK#142]
---
Hello geeks in demo GPS example I'm getting 4 digits in latitude and longitude. like this.
I'm not able to understand why this is happening
`GPS fix:1, BDS fix:1, Latitude:2311.8704, Longitude:07238.2889`

**Comment by Neutree** [comment]
it's from the raw NMEA ouput format, you should learn about NMEA standard,

the log means: gps not fix, bedou not fix, latitude:23°11.8704'。。。。。
