### ISSUE TITLE
e-SIM interface

### ISSUE THREAD

**Issue by updesh31** [Ai-Thinker-Open/GPRS_C_SDK#143]
## 1. SDK version（SDK 版本）

{

SW_V2106_csdk

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
      Is it possible to interface e-SIM with A9G?

}

---

**Comment by Neutree** [comment]
Of course, you can

**Comment by Neutree** [comment]
the same as common SIM
