### ISSUE TITLE
Problem in API_EVENT_ID_SINGNAL_QUALITY

### ISSUE THREAD

**Issue by gsmwhatnot** [Ai-Thinker-Open/GPRS_C_SDK#145]
## 1. SDK version（SDK 版本）

{

V2104

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

On API_EVENT_ID_SINGNAL_QUALITY, pEvent->param2 ( Which is RXQUAL ) always returns 99

Also there is typo in events name 'SINGNAL' -> 'SIGNAL'

}

---

**Comment by Neutree** [comment]
Thanks !!
Modified in latest version

RXQUAL is valid  only when you are making a call
