### ISSUE TITLE
A9 CALL_Dial Problem

### ISSUE THREAD

**Issue by updesh31** [Ai-Thinker-Open/GPRS_C_SDK#148]
## 1. SDK version（SDK 版本）

{

SW_V2107_csdk

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
working on a next project based on A9 module.Received call successfully but when device goes to dial a number always getting an error message given below:
CALL_Dial("+91838485xxxx")
"Hang up,is remote hang up:1, error code:4"

why? 

}

---

**Comment by gsmwhatnot** [comment]
**is remote hang up:1** shows that remote party hung up this call. Remote could be network itself. for example if you don't have enough credit, network gives you "insufficient balance" and hangs up on you or call get rejected by called party etc.

**Comment by updesh31** [comment]
Ok I will test it with other network's SIM.

**Comment by updesh31** [comment]
Not getting success.All other functions are working accelerometer,SMS etc.

**Comment by gsmwhatnot** [comment]
Here are my suggestions :
1. Solder small speaker to the SPK_P and SPK_N of PCB and listen to the operator message ( If there is any )
2. In some countries dialing standard ISDN formatting is not supported (  dialing +91XXX instead of 0091 )

**Comment by updesh31** [comment]
1.In AT command mode command ATD+918384xxxxxx; always works. Why CALL_Dial("+91838485xxxx") is not working?
2.I will check operator message with spk.

**Comment by updesh31** [comment]
Hey thanx 0091 is working :)
