### ISSUE TITLE
gps信息必须通过串口读出解析后再通过Socket_TcpipWrite发送到服务器上面吗

### ISSUE THREAD

**Issue by sqm289798469** [Ai-Thinker-Open/GPRS_C_SDK#15]
gps信息必须通过串口读出解析后再通过Socket_TcpipWrite发送到服务器上面吗

**Comment by Neutree** [comment]
...这个都是功能上的逻辑了，，，看你自己有什么需求咯

**Comment by sqm289798469** [comment]
Socket_TcpipWrite（套接字，数据，数据长度），
gps的demo里，触发gps时间，串口输出是 UART_Write(UART1,pEvent->pParam1,pEvent->param1);
,pEvent->pParam1,pEvent->param1这2个是否就是数据和长度，
对代码这一块真心不懂

**Comment by Neutree** [comment]
。。。。对呀。。在api_event.h中也有说明
![image](https://user-images.githubusercontent.com/8625829/33866542-3bdcff6a-df32-11e7-9a48-9ead5c7fce6a.png)

**Comment by Neutree** [comment]
等会儿我写一个定时发送gps定位信息的demo吧。。。看你搞了这么久都没搞定！！！基础不牢哦，加油

**Comment by Neutree** [comment]
静下心来多看看多谢谢多调试调试代码，大家都是这么一步一步过来的

**Comment by sqm289798469** [comment]
嗯，谢谢，入门硬件这一块才一个多月，先前主要学arduino

**Comment by sqm289798469** [comment]
![image](https://user-images.githubusercontent.com/34051664/33872355-80cb35aa-df51-11e7-9be8-bff3280fc0ae.png)
这是信息丢失了吗？

**Comment by Neutree** [comment]
https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/gps/src/demo_gps.c
写了个定时发送GPS原始信息到串口，可以作为参考
