### ISSUE TITLE
Mqtt ssl timeout error

### ISSUE THREAD

**Issue by Tanukaroy4494** [Ai-Thinker-Open/GPRS_C_SDK#153]
## 1. SDK version（SDK 版本）

{

2.107

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

[

![a9g mqtt error1](https://user-images.githubusercontent.com/39370752/42077945-4af47b2e-7b98-11e8-8308-3d650dfd5fa9.PNG)

![a9g mqtt error 2](https://user-images.githubusercontent.com/39370752/42077984-6cb5be08-7b98-11e8-93e5-68a05bbef443.PNG)

}

---

**Comment by wavresangam** [comment]
hey @Tanukaroy4494  how to solve this i have same problem

**Comment by Tanukaroy4494** [comment]
Change QoS to 1

**Comment by wavresangam** [comment]
@Tanukaroy4494  thank you i will try..
