### ISSUE TITLE
AT+CLCC - GSM 02.30 Standard

### ISSUE THREAD

**Issue by gsmwhatnot** [Ai-Thinker-Open/GPRS_C_SDK#156]
## 1. SDK version（SDK 版本）

{

2104

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

According to GSM 02.30 there is call state implemented in GSM stack, also it can be requested with AT+CLCC command in AT firmware, can we have that feature as an event or function call in the SDK ? the states are as follows : 

<stat> State of the call
- 0 Active
- 1 Held
- 2 Dialing (MO call)
- 3 Alerting (MO call)
- 4 Incoming (MT call)
- 5 Waiting (MT call)

Also it would be great to have full disconnection cause code in SDK, right now there is just few codes like busy, no answer, etc.
}

---

**Comment by Neutree** [comment]
update in v2.1.12
