### ISSUE TITLE
play voice 

### ISSUE THREAD

**Issue by updesh31** [Ai-Thinker-Open/GPRS_C_SDK#157]
## 1. SDK version（SDK 版本）

{

SW_V2108_csdk

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

How can I store and play voice?

}

---

**Comment by Neutree** [comment]
can not yet

**Comment by updesh31** [comment]
When will I get voice store and play feature?
My product is working well and with voice feature expected quantity will be >1000/month.
