### ISSUE TITLE
'sed' is not recognized 

### ISSUE THREAD

**Issue by seym45** [Ai-Thinker-Open/GPRS_C_SDK#166]
SDK version: 2.108

when I run ./build.bat app in windows 10 powershell, the output is 
 
GPRS_C_SDK> .\build.bat app
CSDTK PATH: F:\GPRS_C_SDK
'sed' is not recognized as an internal or external command,
operable program or batch file.
'sed' is not recognized as an internal or external command,
operable program or batch file.
build folder exist
number of processors: 4

Can anybody help me with installation, please?

**Comment by gsmwhatnot** [comment]
According to this section https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/installation.html#installation double check that you have run as administrator this file `config_env_admin.bat`. It is better to restart your windows to make changes effective.
Also check in your Windows path if it is pointed to the `CSDTK4.2` folder. I believe you can run this command inside power shell to get you environment path : `echo %PATH%`

**Comment by seym45** [comment]
Thank you, after the restart, It worked, thank you 👍 💯
