### ISSUE TITLE
能用SDK连接机智云吗？

### ISSUE THREAD

**Issue by the-linke2016** [Ai-Thinker-Open/GPRS_C_SDK#17]
# 之前用AT连接过，不知道用SDK行不行？

**Comment by Neutree** [comment]
目前还木有弄进去

**Comment by the-linke2016** [comment]
也是用过Socket实现的吗？

**Comment by Neutree** [comment]
是的

**Comment by the-linke2016** [comment]
期待尽快加入！

**Comment by iZhangHui** [comment]
@Neutree 非常期待这个功能！

**Comment by iZhangHui** [comment]
@Neutree 您好，年前买了两块A9G开发板做测试，功能非常强大，使用也非常方便．
我们的项目有使用机智云的需求，按照您的教程非常方便的就可以完成定位信息的上传．
另外项目需要采集其他传感器的数据，出于成本考虑再搭配一个mcu，显然不划算．
能否优先将此部分功能添加到SDK呢？谢谢．

**Comment by Neutree** [comment]
已加入
