### ISSUE TITLE
fotacreate.exe not working on Windows 7

### ISSUE THREAD

**Issue by updesh31** [Ai-Thinker-Open/GPRS_C_SDK#171]
## 1. SDK version（SDK 版本）

{

SW_V2110_csdk

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
![image](https://user-images.githubusercontent.com/39764903/43049046-239fc31a-8e0f-11e8-9ca9-f7c15bc840d9.png)

then I copy and paste MSVCP140.dll in fota folder after that I am getting 

![image](https://user-images.githubusercontent.com/39764903/43049077-7019c7c2-8e0f-11e8-8cdf-9e4b9d100760.png)

}

---

**Comment by gsmwhatnot** [comment]
That't because Microsoft Visual C++ 2015 Redistributable is not installed on your windows. Install it from link bellow : 
https://www.microsoft.com/en-us/download/details.aspx?id=53840

P.S : Close your tickets if they are solved.
