### ISSUE TITLE
store .amr files

### ISSUE THREAD

**Issue by updesh31** [Ai-Thinker-Open/GPRS_C_SDK#177]
## 1. SDK version（SDK 版本）

{

SW_V2112_csdk

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

Is it possible to save .amr file through UART?

}

---

**Comment by Neutree** [comment]
you can just send record data to uart while recording, by use data callback while recording:
```
void CallbackData(unsigned char* data, unsigned int len, unsigned int* recordLen)
{

//send voice data here

    *recordLen = len;
}

AUDIO_Error_t result =  AUDIO_RecordStart(AUDIO_TYPE_AMR,AUDIO_RECORD_MODE_AMR122,recordFd,CallbackResult,CallbackData);
```
