### ISSUE TITLE
新demo_gps下载出错

### ISSUE THREAD

**Issue by sqm289798469** [Ai-Thinker-Open/GPRS_C_SDK#18]
Detected XCPU in the GDB loop (0x9db00000), connect GDB debugger for more info.

调试demo_gps老出现这个，没改过程序

**Comment by Neutree** [comment]
这应该是程序死机了，看看是不是哪里指针错误

**Comment by sqm289798469** [comment]
更新的GPS解析是怎么回事，下载新的demo_gps，串口能输出的还是未解析的信息

**Comment by Neutree** [comment]
自己看程序嘛，年轻人别急躁，看看代码逻辑是怎么写的，都帮你写了还懒得看

**Comment by Neutree** [comment]
你还有什么需求？我全部帮你写完好了
