### ISSUE TITLE
GPS langitude and longitude does not change

### ISSUE THREAD

**Issue by Tanukaroy4494** [Ai-Thinker-Open/GPRS_C_SDK#182]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

![image](https://user-images.githubusercontent.com/39370752/43442589-03ecd838-94bc-11e8-8be9-e3227de34da1.png)

Even in open area it gives the same. What can be the reason?

}

---

**Comment by Neutree** [comment]
not fix yet according to you pic, check you antenna，stick a picture here about your dev board and connection of antenna

**Comment by Tanukaroy4494** [comment]
Hi, I am using A9G development board, trying to code using CSDK. 
![d33fb0b5eb67b9fd2afe23fd91d00e676e1cb80c4939d647ba pimgpsh_mobile_save_distr](https://user-images.githubusercontent.com/39370752/43451472-a5aebad6-94d2-11e8-8a3e-1bb92b0772e7.jpg)

USB TX->HST_RX
USB RX-> HST_TX
External VCC->VUSB
External GND->GND

**Comment by punee995** [comment]
try testing it on open area or near window!

**Comment by punee995** [comment]
of if you have active antenna then it woks like charm.

**Comment by Tanukaroy4494** [comment]
Problem was with the power supply , it was not getting enough. Thank you.

**Comment by Marklanet** [comment]
how much power supply did you give for it to function well...the voltage and current
