### ISSUE TITLE
A9g stuck in between of firmware burning.

### ISSUE THREAD

**Issue by fu-techiot** [Ai-Thinker-Open/GPRS_C_SDK#185]
**Hello There,**
As shown in the image I got an error like this while using COOLWATCHER to burn firmware or code,
`

`[]': bignum too big to convert into `long' (RangeError)
--

`

![a9g upload error](https://user-images.githubusercontent.com/38309034/43512791-add016fc-9599-11e8-8db7-8fd2531b2340.png)

**this issue occurs in NEW UPDATED SDK ONLY...**
so what is the issue can anyone tell me?

**Comment by punee995** [comment]
update CSDTK

See : https://github.com/Ai-Thinker-Open/GPRS_C_SDK/releases
