### ISSUE TITLE
OS_QueryCallbackTimer return value

### ISSUE THREAD

**Issue by Tanukaroy4494** [Ai-Thinker-Open/GPRS_C_SDK#189]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

After calling OS_StartCallbackTimer to know how much time is left i am calling OS_QueryCallbackTimer which returns value somewehat this "163222" and this changes everytime. I want to know if i am doing it right and Is the value being returned by OS_QueryCallbackTimer  in ms?

}

---

**Comment by punee995** [comment]
see documentation ->
https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/function-api/os.html#osquerycallbacktimer
