### ISSUE TITLE
Typo's and missing documentation for the time API.

### ISSUE THREAD

**Issue by mrgreywater** [Ai-Thinker-Open/GPRS_C_SDK#192]
## 1. SDK version（SDK 版本）
V2.112
---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）
Time API.

The time API seems weird and not correctly documented:
- [time.h#L15](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/include/std_inc/time.h#L15) `TIME_GetIime` should be `TIME_GetTime`
The time returned seems to have an offset of 946684800 from epoch, so it returns the time in seconds from 1/1/2000 12:00AM UTC. Maybe this info could be added to the documentation.
- [time.h#L16](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/include/std_inc/time.h#L16) `TIME_GetRtcTIme` should be `TIME_GetRtcTime`
- The time from `time(NULL)` appears to be in seconds from epoch, but in the local time zone.
Usually, in the C standard, it's should not be locally adjusted, but in the UTC time zone. 
---

**Comment by Neutree** [comment]
Thanks!

That's right the `TIME_GetTime` return seconds from  2000-1-1 00:00:00 UTC.

And `time(NULL)` return seconds from 1970-1-1 00:00:00 CST(China Standard Time UTC+8:00), it will be changed  to UTC the next version

**Comment by Neutree** [comment]
I made some update here: https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/time/src/demo_time.c
