### ISSUE TITLE
http POST with Header for https !!

### ISSUE THREAD

**Issue by Bhavikjp** [Ai-Thinker-Open/GPRS_C_SDK#193]
In the example of **gps_tracker**, how to add **Headers** for https.
![post](https://user-images.githubusercontent.com/38308759/43817091-6da4daf2-9af5-11e8-88f9-be66f31b4440.png)

There is given only no header example,
Suggest a way to add the header with it.

**Thanks!!!**

**Comment by Neutree** [comment]
If you know how http consist of, everyting will be easy,
e.g.
```
GET / HTTP/1.1
Host: www.example.com
Cache-Control: no-cache


```

**Comment by Bhavikjp** [comment]
Yes..
I have used incorrect authorization..later on i have recreate it and it works well.
Thanks for replying!!
