### ISSUE TITLE
Trigonometric functions not implemented

### ISSUE THREAD

**Issue by mrgreywater** [Ai-Thinker-Open/GPRS_C_SDK#195]
## 1. SDK version（SDK 版本）

V2.112

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）
Trigonometric functions are declared in "math.h" but are not actually defined in the library. Therefore it will not compile.

```cpp
#include "stdint.h"
#include "stdbool.h"
#include "stdlib.h"
#include "stdio.h"
#include "api_debug.h"
#include "api_os.h"
#include "api_event.h"
#include "math.h"
#include "sdk_init.h"
#include "limits.h"
#include "float.h"
#include "time.h"

void app_Main()
{
    Trace(1,"sqrt:%f", sqrt((double)clock()));
    Trace(1,"sin:%f", sin((double)clock()));
    Trace(1,"cos:%f", cos((double)clock()));
}
```
will result in the following error:
```
app_main.c:32: relocation truncated to fit: R_MIPS16_26 against `sin'
app_main.c:33: undefined reference to `sin'
value:0, p:ffffffff88240932, addend:0, symbol:0
app_main.c:33: relocation truncated to fit: R_MIPS16_26 against `sin'
error:34: undefined reference to `cos'
value:0, p:ffffffff8824094a, addend:0, symbol:0
error:34: relocation truncated to fit: R_MIPS16_26 against `cos'
app_main.c:34: undefined reference to `cos'
value:0, p:ffffffff88240962, addend:0, symbol:0
app_main.c:34: relocation truncated to fit: R_MIPS16_26 against `cos'
error:35: undefined reference to `sqrt'
value:0, p:ffffffff882409c0, addend:0, symbol:0
error:35: relocation truncated to fit: R_MIPS16_26 against `sqrt'
error: undefined reference to `sqrt'
value:0, p:ffffffff882409da, addend:0, symbol:0
app_main.c:35: relocation truncated to fit: R_MIPS16_26 against `sqrt'
```

---

**Comment by mrgreywater** [comment]
Yes, it's the latest github (recursive) clone with the SDTK 4.2. But i will retry on a different clean machine soon, just to be sure.

**Comment by gsmwhatnot** [comment]
Like I said in posts before, this is caused by some missing CFLAG option of -lm ( -LM ) in build rules. I tried adding it but it didn't work so I asked Neutree to look into it.

My post : https://github.com/Ai-Thinker-Open/GPRS_C_SDK/issues/169#issuecomment-408635957

**Comment by Neutree** [comment]
OK, I'll check it

**Comment by Neutree** [comment]
@mrgreywater @gsmwhatnot  
I made some fix, now you can use the variable in the math function!

**Comment by reallyczx** [comment]
I'm having the same issues.how am I to solve it?

**Comment by reallyczx** [comment]
这个问题是怎样解决的，我使用的是V2.112，问题同样存在？

**Comment by reallyczx** [comment]
这个问题修复发布在那个版本里？
