### ISSUE TITLE
Firmware not updating using demo/FOTA

### ISSUE THREAD

**Issue by Tanukaroy4494** [Ai-Thinker-Open/GPRS_C_SDK#198]
<
I am trying to use FOTA but firmware does not get upgraded.Why? I have followed all the steps from document provided.

![image](https://user-images.githubusercontent.com/39370752/44075041-d54f3dd8-9fb8-11e8-852b-8de2086b349a.png)

I am getting response code 200 and proper content length.Immeadiate help will be appreciated.Thanks in advance.

@Neutree pLEASE HELP!

}

---

**Comment by punee995** [comment]
did you follow this?
https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/function-api/fota.html

**Comment by Tanukaroy4494** [comment]
@punee995 Yes i did, I am getting proper content length but data isn't as given in my query. Besides response for **API_FotaReceiveData(unsigned char *data, int len)**  is **0**.

**Comment by punee995** [comment]
same as #133.
I say read doc carefully.

**Comment by Tanukaroy4494** [comment]
@punee995 @Neutree If it encounters space in .pack file , it does not read data further.

**Comment by punee995** [comment]
it bad manner to use space in URL.
but if you want to use space then you can simply replace space with **"%20"**.
e.g. file **"V3.0 to new.pack"** will be http://xyx.com/V3.0%20to%20new.pack

**Comment by Tanukaroy4494** [comment]
@punee995 my url is **http://api.atozinfoway.in/Prod/IOT/%stonew.pack**  Data inside is
**RDAOTA01T±´}     $ Á[/î¨  ]   d$       0 ¾33” Xè%§¸LÀ
[ÊÉV~íC“N÷·'æ’$!òX’;/ÞÂ7	ûv?–i†@>>Îõ,¸¤I4"C|‘WR«”qhìe–w11Ì–	¯-kSÇÁåà:ØøZGw@2ž&FŽ,çù;ú
~ç!Q±FÓ©`Z0äÊ+¤åÂ¸	×ÈÇ™¤Áw÷S\ÿ1>2þIÂ–¡Mz~4ÆVŸ‰ætè½®•nK´2¢È±‚ÌêÙXÄšH²#h\²Çð$^˜>zlÍ.Ïs%¹Úd#CQ1xi}•èØáA£ëp^*Þ{	¸Ò¬×
?vºØœ”*[ìœŸ‘Bß”Ki”®¢k{¥sž]’ú¯2ëé•¡Ê8û*Ï±måqEÏïgï='‡îÀkµM{>ŠrÎ‹KÓèsù¥æeÂ#Ö"Lõ±Õ+ìâùÈ µÍm)>KfBÿ“øqxYøÍÿ•(F©ü|Þûš0.VÀ…óƒÀeÄ%Søõ‘61¥°îoÁpMGÑ‘ª­`ºÎ±'\Y†éfRX¾év¬Yäå[ùÇÚ­üûR+tÍ[ BùÝS=ø)d	;€Ë*lßµ;ðÄ½._ª>KfBÿ“øqxYøÍÿ•(F©ü|Þûš0.VÀ…óƒÀeÄ%Søõ‘61¥°îoÁpMGÑ‘ª­`ºÎ±'\Y†éfRX¾év¬Yäå[ùÇÚ­üûR+tÍ[ BùÝS=ø)d	;€Ë*lßµ;ðÄ½._ª>KfBÿ“øqxYøÍÿ•(F©ü|Þûš0.VÀ…óƒÀeÄ%Søõ‘61¥°îoÁpMGÑþAe** 

It only takes data till  "RDAOTA01T±´}". Why?

**Comment by punee995** [comment]
my output (Working!)
![image](https://user-images.githubusercontent.com/7541915/44569906-818aeb00-a799-11e8-9118-fcda194ff94c.png)

**Comment by Tanukaroy4494** [comment]
@punee995  Can power be the issue?

**Comment by punee995** [comment]
mailed working lod files.

**Comment by Tanukaroy4494** [comment]
Thank you so much

**Comment by will88china** [comment]
@punee995  I have also worked not well,  even the reference code is also abnormal,could you tell me how solve it?thanks.
![image](https://user-images.githubusercontent.com/40222757/56018380-8efae280-5d34-11e9-9519-2efa067278f6.png)

**Comment by will88china** [comment]
@punee995  could you mail me the working log files too? 172980751@qq.com, thanks so much.

**Comment by Tanukaroy4494** [comment]
@will88china Make sure your device has the same firmware build which you used while creating new firmware

**Comment by will88china** [comment]
@Tanukaroy4494 yes, according to the online SDK,  I have just modified the version number between old and new firmware, but it always got "fota fail" after  network activate success, I have tried demo code both from SDK  or punee995, but  got same fails, thanks.

**Comment by LubomirBogdanov** [comment]
I also experience the same problem. it appears that this function fails:

API_FotaReceiveData( )

in processFotaUpgradeData( ). I also cannot understand what is the purpose of having two defines:

#define SOFT_VERSION          "V1.0.0"
//#define SOFT_VERSION          "V2.0.0"
#define FOTA_HTTP_SERVER      "http://mysite/%sfota.pack"

instead of:

#define SOFT_VERSION          "V1.0.0"
#define FOTA_HTTP_SERVER      "http://mysite/V2.0.0fota.pack"

**Comment by MaxBoyman** [comment]
whats the problem with FOTA i exactly did what it said in the [FOTA section of document](https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/function-api/fota.html) it doesn't work.
![Annotation 2019-12-22 161935](https://user-images.githubusercontent.com/24266760/71322020-73f18c80-24d7-11ea-891a-b11df6d1abf6.png)
what should i do with this.
i will say what i found from the documentation briefly:
1- cleaning hex folder by "./build.bat clean"
2- compiling code with "./build.bat demo fota" without considering that if it is a realese or debug version
3- back up the hex/fota folder somewhere else and copy fota_*_debug_ota.lod to GPRS_CSDK/ then rename it to old.lod
4- changing whatever you want to provide after program update. for example changing version by modifying SOFT_VERSION from "V3.0" to "V3.1".
5-cleaning hex/fota directory and compiling again without considering that if it is a realese or debug version
6-copy fota_*_debug_ota.lod to GPRS_CSDK/  and rename it to new.lod
7- executing batch with this code: ./build.bat fota old.lod new.lod V3.0tonew.pack
8- uploading V3.0tonew.pack to the host you provided it's link in code.
9- uploading code to A9 or A9G and waiting for update.
I did this procedure with no success. First i used an https server but then i changed the server security to http. again with no success.
