### ISSUE TITLE
a9g关于低功耗应用

### ISSUE THREAD

**Issue by chenxiuqimr** [Ai-Thinker-Open/GPRS_C_SDK#2]
二次开发，如何让a9g进入最低功耗呢？我们项目需要用电池供电，就是定期采集下几个传感器的数据和gps位置数据并上报到服务器，然后就让a9g进入最低功耗，时间到了再唤醒自己再采集一次数据并上报，如此循环。好像目前没有文档说到如何进入低功耗和如何定期唤醒的，多谢指导!

**Comment by Neutree** [comment]
下个版本加入，预计本周内

**Comment by Neutree** [comment]
[低功耗](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/pm/src/demo_pm.c)
