### ISSUE TITLE
SMS_DeleteMessage Doesn't Work!!!

### ISSUE THREAD

**Issue by Bhavikjp** [Ai-Thinker-Open/GPRS_C_SDK#201]
**Hello,**

index=5 in SMS_delete function. Stored SMS=4, SMS delete success. But didn't get deleted.
**how to delete all SMS at the same time. as well as one by one.**

![sms1](https://user-images.githubusercontent.com/38308759/44305068-7a746f00-a38c-11e8-90c0-947a5b0b9e39.png)

![sms2](https://user-images.githubusercontent.com/38308759/44305071-7c3e3280-a38c-11e8-9141-cb74c2db88a6.png)

![sms3](https://user-images.githubusercontent.com/38308759/44305072-7e07f600-a38c-11e8-9f60-781c789357d1.png)

**Actually what index does in that function?**

**Thanks!!**

**Comment by Bhavikjp** [comment]
@Neutree @punee995 
how to delete all SMS at the same time. as well as one by one.

**Thanks!!**

**Comment by punee995** [comment]
I think you're getting it wrong!
if **index_value=5** then it delete **5th message** will be deleted.

i think A9G can store up to ~48 message.
to delete all message you can run **for loop** for 48 times.

**Comment by Bhavikjp** [comment]
Yes.later on i have used for loop and it works well.
Thanks for replying!!

**Comment by locorcor** [comment]
Hi Bhavikjp, could you post an example of the loop?  thank you in advance!!!

**Comment by elangovan27sri** [comment]
> Hi Bhavikjp, could you post an example of the loop? thank you in advance!!!

hope he used to loop on the sim card that stored messages, not with flash memory.. delete message function on flash is having a bug I believe.

read this..
https://github.com/Ai-Thinker-Open/GPRS_C_SDK/issues/342
