### ISSUE TITLE
FS API Filename - Problem with creating files starting with letter "T"

### ISSUE THREAD

**Issue by gsmwhatnot** [Ai-Thinker-Open/GPRS_C_SDK#209]
## 1. SDK version（SDK 版本）

{

2.108

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

This is very odd, but I did not have any success creating files inside FLASH with their name starting with "t". For example you can't read/write/create filename `/table.conf` . The `API_FS_Open` function always returns error but this will not happens with any other letters.

I think this problem happens because SD FLASH folder to read/write files from TF FLASH is starting with "/t"

}

---

**Comment by Neutree** [comment]
right ! but the latest version fixed this bug
