### ISSUE TITLE
下载调试GBD

### ISSUE THREAD

**Issue by sqm289798469** [Ai-Thinker-Open/GPRS_C_SDK#21]
![image](https://user-images.githubusercontent.com/34051664/34193387-5bdcf0b0-e58e-11e7-88e8-cae9fedfca66.png)

不太明白这个，网上找了相关资料，还是模糊
是我程序出问题还是怎么了

**Comment by Neutree** [comment]
额，这个GDB确实不是很好用，但是大概可以知道你的Socket_TcpWrite()函数这里出错了，检查一下有没有指针越界的可能

**Comment by sqm289798469** [comment]
我是修改demo的socket，只是把Socket_TcpWrite()单独领出来建立个任务来输出字符串
void tcp_testTask(void *pData)
{
    while(1)
    {
        Socket_TcpipWrite(socketFd,"hello world\n",strlen("hello world\n"));  
        OS_Sleep(10000);
    }
}
偶尔能下载程序，正常发送信息到tcp

**Comment by Neutree** [comment]
能用这个的前提是GPRS网络已经激活并且已经成功建立了socket连接，不知道是不是写了，请仔细看例程！！

**Comment by sqm289798469** [comment]
当然已经激活并连接，不然我tcp也接受不到，就是GPS信息数据发送到TCP的时候，老提示错误，应该是你说的指针越界，但我找半天没发现错在哪，和UART的输出方式有什么需要注意的吗？
