### ISSUE TITLE
Request GPRS-C-CSDKfunction for using onboard- EEPROM or onboard flash mem.

### ISSUE THREAD

**Issue by TridentTD** [Ai-Thinker-Open/GPRS_C_SDK#210]
Sometime makers want to save private data 
to the onboard-EEPROM ( or sth. like that such as onboard- flash mem. ) 
not to SD card.

However at now, GPRS-C-CSDK  seem 
doesn't have any some functions for using it.

Request GPRS-C-CSDK support them too.
Thank you.

**Comment by Neutree** [comment]
you just didn't read doc or code , supported
