### ISSUE TITLE
Where do I create the comport symbolic link?

### ISSUE THREAD

**Issue by cryarchy** [Ai-Thinker-Open/GPRS_C_SDK#223]
SDK version = V2.112
---
Problem occurs when creating the comport symbolic link  with `sudo ln -s /dev/ttyUSB0 comport/COM1`
```
ln: failed to create symbolic link ‘comport/COM1’: No such file or directory
```
---

**Comment by Neutree** [comment]
plug in your serial tool( USB to TTL) firstly, and `ls /dev/ttyUSB*` to ensure the device( file) exist

**Comment by Neutree** [comment]
`mkdir comport` firstly

**Comment by Neutree** [comment]
cd CSDTK4/cooltools/
mkdir comport

**Comment by cryarchy** [comment]
Thank you!
