### ISSUE TITLE
AT+GIZTRACKER命令能支持把数据报给自己的服务器吗？

### ISSUE THREAD

**Issue by xiaojianbj** [Ai-Thinker-Open/GPRS_C_SDK#23]
看说明把server参数设为1就行，但在哪设置上报服务器的ip，端口，还有上报的消息包格式是怎样的？

**Comment by Neutree** [comment]
这里是CSDK项目，AT指令相关的请不要在这里提问

这是使用了机智云的服务器，所谓的自定义服务器不是用你自己的服务器，而是你自己去机智云上面注册账号，并且创建产品，它会给你product key 和 product secret
