### ISSUE TITLE
A9G Gives Fix Speed!! Speed Doesn't Change!!!

### ISSUE THREAD

**Issue by Bhavikjp** [Ai-Thinker-Open/GPRS_C_SDK#234]
Hello,
I have used the following function for the speed

`snprintf(mydata, sizeof(mydata), "{\"Timestamp\":%s,\"Speed\":%f,\"Altitude\":%f,\"Latitude\":%f,\"Longitude\":%f,\"battery\":%.1f,\"VehicleId\":\"Test1\"}", timestamp, isFixed*1.0, gpsInfo->gga.altitude, latitude, longitude, percent*1.0);`

Function for speed:  isFixed*1.0

But I got always either 1.0 or 3.0 speed every time.
***How to get real-time varying speed?***

Thanks!!

**Comment by kaido42** [comment]
isFixed is 3 when there is gps fix, 1 otherwise.

use gpsInfo->vtg.speed_kph for speed (km/h)

**Comment by Bhavikjp** [comment]
@kaido42 
Thanks for immediate reply!!

GPS fix mode:3, BDS fix mode:3, fix quality:1, satellites tracked:4, gps sates total:12, is fixed:3D fix, coordinate:WGS84, Latitude:24.945690, Longitude:74.519893, unit:degree,altitude:0.000000

I got 3D fix, Fix Mode:3, Proper LatLong.
But still got Speed:0.00000
ofcourse i am moving:)

how can  i get realistic speed?

**Thanks!!**

**Comment by kaido42** [comment]
>> gpsInfo->vtg.speed_kph

note that this is not float, so you cannot print it with %f .. 

there is a function to convert:

double nmeafloat_2_float (struct minmea_float value) {
    if (value.scale) {
        return 1.0*value.value/value.scale;
    } else {
        return 0;
    }
}

use as follows:

snprintf (... , "speed: %f", nmeafloat_2_float(gpsInfo->vtg.speed_kph));

**Comment by Bhavikjp** [comment]
@kaido42 

It works now!!

Thank you so much!!

**Comment by andyman2240** [comment]
@kaido42
Could you show me how to get time and date from GPS NMEA sentences such as  $RMC or $ZDA? I have had limited success when using:  snprintf(buffer4,sizeof(buffer4),"Time: %d",gpsInfo->rmc.time);   even when I have GPS lock (10-12 satellites).

**Comment by ji4a** [comment]
@Bhavikjp @kaido42 

I am using /demo/gps_tracker/demo_gps_tracker.c
on line 373:

```
snprintf(requestPath,sizeof(buffer2),"/?id=%s&timestamp=%d&lat=%f&lon=%f&speed=%f&bearing=%.1f&altitude=%f&accuracy=%.1f&batt=%.1f",
                                                    buffer,time(NULL),latitude,longitude,isFixed*1.0,0.0,gpsInfo->gga.altitude,0.0,percent*1.0);
```

I don't get the actually speed in km/h. it sticks on Speed: 1.85 km/h
How can i modify the code to get realistic speed?
