### ISSUE TITLE
FCS A9G demo call not working

### ISSUE THREAD

**Issue by slowkazak** [Ai-Thinker-Open/GPRS_C_SDK#239]
## 1. SDK version（SDK 版本）

{

V2112
}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
burn call demo 
FCS error. Rcv : 0xBC 0xA8 0xD0, calc : 0xCE 0xB4 0x85
No calling. What happend?

}

---

**Comment by punee995** [comment]
Assuming you modified [demo_call.h](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/8e7f95b90e92bfc4839e691c57727f6f107799fb/demo/call/include/demo_call.h#L4) to your cell no.
also try adding county code!
if it doen't help please give full log from csdk.
