### ISSUE TITLE
No function for HTTP_GET!!!

### ISSUE THREAD

**Issue by Bhavikjp** [Ai-Thinker-Open/GPRS_C_SDK#244]
Hello,

**I need to call HTTP_GET API of my server.**
But there is the only function for http_post.
How to call GET API?

**Is there any function for GET_HTTP?**

Thanks!!!

**Comment by Ricx8** [comment]
I believe there is one in the socket example 
Here: https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/socket/src/demo_socket.c
Line 112
