### ISSUE TITLE
为什么我的板子ADC0和ADC1的内阻不一样？是不是这块板子有问题？

### ISSUE THREAD

**Issue by will88china** [Ai-Thinker-Open/GPRS_C_SDK#283]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

}

---

**Comment by punee995** [comment]
please close the issue if your problem is solved!
