### ISSUE TITLE
coolwatcher undefined methode 

### ISSUE THREAD

**Issue by wavresangam** [Ai-Thinker-Open/GPRS_C_SDK#285]
## 1. SDK version（SDK 版本）

{

V2.112

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

when i am trying to burn firmware or restarting module it gives an error 

" undefined method 'CHST_Read32' for #<CHHostConnection:0x7f6b0e8c37c0> (NoMethodError) "

what it means ??

help me to solve this 

}

---

**Comment by natrayanp** [comment]
Getting the same error in Linux (Ubuntu 20.04).  How to solve this issue?
