### ISSUE TITLE
A9G's firmware verification error when download finished.

### ISSUE THREAD

**Issue by yoyojacky** [Ai-Thinker-Open/GPRS_C_SDK#287]
## 1. SDK version（SDK 版本）

{

firmware: **Ai-Thinker_A9_A9G_AT_V02.02.20180825R.afw**
GPS firmware: **GK9501_Release_GB_1.4_20180224.bin** 
Download tools:  **AI-thinker GSM&GPS Download tool v02.00.01** 

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

we are using the A9G module to build our products ,and we are using this firmware which is download from your official website:   Ai-Thinker_A9_A9G_AT_V02.02.20180825R.afw
and GPS hex binary file : GK9501_Release_GB_1.4_20180224.bin 
using your Download tools: AI-thinker GSM&GPS Download tool v02.00.01 
on my windows 10 PC with administrator privilleges.  
![image](https://user-images.githubusercontent.com/6893075/50672738-da567400-1014-11e9-89d1-7fbbeb9139f3.png)
and it can be download to module, but after downloading, it appears a warning:  
![image](https://user-images.githubusercontent.com/6893075/50672764-f35f2500-1014-11e9-8079-e0af18c9f18d.png)

and we are trying several times, please help me!
thanks a lot!
}

---

**Comment by Ogauy** [comment]
Please use the official software

**Comment by Ogauy** [comment]
https://pan.baidu.com/s/16ZIQ9YbZdcVz-zvpzEFXbA

**Comment by NerdBishop** [comment]
anyone with a link to the flash tool? and the firmwire?

**Comment by VermaAyush** [comment]
please give the link of new firmware, The official Ai thinker wesite https://docs.ai-thinker.com/_media/gprs/ai-thinker_a9_a9g_at_v02.02.20190915r.rar file is corrupted. if anyone have working downloaded firmware

**Comment by dipinraj** [comment]
> please give the link of new firmware, The official Ai thinker wesite https://docs.ai-thinker.com/_media/gprs/ai-thinker_a9_a9g_at_v02.02.20190915r.rar file is corrupted. if anyone have working downloaded firmware

Same issue here ! Any idea, where I can get firmware?

**Comment by dipinraj** [comment]
> please give the link of new firmware, The official Ai thinker wesite https://docs.ai-thinker.com/_media/gprs/ai-thinker_a9_a9g_at_v02.02.20190915r.rar file is corrupted. if anyone have working downloaded firmware

Try different browser.I got resolved that way !

**Comment by yoyojacky** [comment]
problem resolved. thanks for tips.
