### ISSUE TITLE
SDK中LCD接口未开放

### ISSUE THREAD

**Issue by ReleaseBug** [Ai-Thinker-Open/GPRS_C_SDK#293]
SDK version（SDK 版本）：V2112
模块支持LCD屏（GPIO14/15/16/17/18），SDK中没有对应接口，能否提供LCD显示屏的例程？

**Comment by Ogauy** [comment]
最新的SDK，好像有相关的demo,尝试更新一下

**Comment by ReleaseBug** [comment]
**Good !** 最新代码里有对应的lcd显示的例程了。3Q~~ @Ogauy
