### ISSUE TITLE
mips-elf-gcc: Command not found on Debian 9 (stretch)

### ISSUE THREAD

**Issue by digitaico** [Ai-Thinker-Open/GPRS_C_SDK#302]
SDK V2.112
OS Linux Debian 9 - Stretch (4.9)
Linux Kernel: 4.9.0-8amd64

After following strictly up to the letter your installation guide,  I found impossible to compile. I'm attaching a screenshot, the test is this:

![screenshot from 2019-01-26 17-02-40](https://user-images.githubusercontent.com/8643845/51793469-fcb05d00-218e-11e9-96c2-411bb8029bb6.png)

```
param number:2
compileMode:debug
compile project gpio
compile path /home/jea/projects/GPRS_C_SDK/demo/gpio
core number:8
Build host is LINUX

MAKE              init
CC                sdk_init.c
make[3]: mips-elf-gcc: Command not found
/home/jea/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:958: recipe for target '/home/jea/projects/GPRS_C_SDK/build/gpio/init/obj/debug/sdk_init.o' failed
make[3]: *** [/home/jea/projects/GPRS_C_SDK/build/gpio/init/obj/debug/sdk_init.o] Error 127
make[3]: *** Waiting for unfinished jobs....
/home/jea/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:975: recipe for target 'dependencies' failed
make[2]: *** [dependencies] Error 2
/home/jea/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:718: recipe for target '/home/jea/projects/GPRS_C_SDK/build/gpio//gpio.srec' failed
make[1]: *** [/home/jea/projects/GPRS_C_SDK/build/gpio//gpio.srec] Error 2
/home/jea/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:371: recipe for target 'lod' failed
make: *** [lod] Error 2
=== Build Time: 0s at 2019-01-26 17:07:37 ===
!!!!!!!!!!!!!!!!!!!!
   BUILD FAILED
!!!!!!!!!!!!!!!!!!!!
```

After reading similar issues on github, Iǘe strictly followed up your instructions.
In one issue pointing to the same problem you recommended:
1) Make sure you ran setup.sh from CSDTK.
Yes I did,  and response was succesful.

2) Make sure you have GPRS CSDTK in your bashrc.  Yes it is: 

```
###############GPRS CSDTK#############                                                                                                                                                                         

alias work='source .//cygenv.sh'                                                                                                                                                                               
export GPRS_PROJ_ROOT=/home/jea/projects/                                                                                                                                                                      
export PATH=$PATH:.//bin:.//mingw32/usr/bin:.//mips-rda-elf/bin:.//rv32-elf/bin                                                                                                                                
export PATH=$PATH:.//cooltools                                                                                                                                                                                 
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:.//lib:.//mingw32/usr/lib                                                                                                                                            
############GPRS CSDTK END############  
```                          

3) Make sure you opened a new terminal session after this:  Yes opended again and even updated and rebooted laptop.

Also installed or required dependencies.  
When extracting Chain Tool,  the last lines of the log are attached.
![screenshot from 2019-01-26 16-58-51](https://user-images.githubusercontent.com/8643845/51793465-e6a29c80-218e-11e9-9b9f-4f6982ddd8ec.png)

So guys,  how can I make this work, if everything looks Ok.  Thanks for your help,  I really appreciate your A9G and want and need to make it work.  

---

**Comment by digitaico** [comment]
Todya I have checked that gcc is installed,  for Debian there is no packages called mips-elf-gcc, most related could be gcc-mips-linux-gnu which Iǘe installed succesfully.

**Comment by digitaico** [comment]
there is also installed libc6-mips.cross,  for cross compiling, ver 2.24-10cross1

**Comment by lsaavedr** [comment]
can "find" the location of these comand and add these location to the "path" of you user? please, that is a basic linux job...

**Comment by digitaico** [comment]
@lsaavedr, yes is located on ~/software/CSDTK/bin/

**Comment by digitaico** [comment]
@lsaavedr is this the correct way to add $PATH in .bashrc?
export PATH=$PATH:.//home/jea/software/CSDTK/bin/

**Comment by digitaico** [comment]
@lsaavedr after exportin $PATH this way:
export PATH=/home/jea/software/CSDTK/bin:$PATH ,
and compiling now the previous "mips-elf-gcc command not found" is gone,  however, now I receive a new error:  check attached screenshot please.
![screenshot from 2019-01-28 17-11-57](https://user-images.githubusercontent.com/8643845/51869951-395f8e00-2320-11e9-97ba-3c4ce08c8899.png)

**Comment by lsaavedr** [comment]
try with this:

```#bash
###############GPRS CSDTK#############
export GPRS_CSDTK42_PATH=/home/jea/software/CSDTK
export GPRS_PROJ_ROOT=/home/jea/projects
alias work='source ${GPRS_CSDTK42_PATH}/cygenv.sh'

export PATH=$PATH:${GPRS_CSDTK42_PATH}/bin:${GPRS_CSDTK42_PATH}/mingw32/usr/bin
export PATH=$PATH:${GPRS_CSDTK42_PATH}/mips-rda-elf/bin:${GPRS_CSDTK42_PATH}/rv32-elf/bin
export PATH=$PATH:${GPRS_CSDTK42_PATH}/cooltools
############GPRS CSDTK END############
```

and check that your shell is bash!

PD: you should try to understand what is in your bashrc!

**Comment by digitaico** [comment]
All this issues have been succesfuly solved!

**Comment by santi10ks** [comment]
@digitaico Could you help me please, I have the same problem

**Comment by digitaico** [comment]
@santi10ks after installing and makeing changes my debian OS got crushed by conflicting packages and dependencies.  The source of all issues is that the sdk needs some 32bit packages, hence the conflicts and problems.  My best recommendation is to create a Docker with the SDK and 32bits OS,  in that way your local machine can't be compomised.
