### ISSUE TITLE
module crashes when length of apn name is less than 3 characters

### ISSUE THREAD

**Issue by jniewerth** [Ai-Thinker-Open/GPRS_C_SDK#304]
## 1. SDK version（SDK 版本）

{

master

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

Network_StartActive on a PDP-Context crashes the module when the APN name has only two characters. E.g. "ap".

Can be reproduced easily by changing the APN in the socket example to "ap".

(OS_Free raises SWI)

}

---

**Comment by PostconEssen** [comment]
You can use "ap ", then it works.
My APN was "tm" and with "tm " it works fine!

[https://github.com/Ai-Thinker-Open/GPRS_C_SDK/issues/262](url)

**Comment by jniewerth** [comment]
Duplicate of #262

**Comment by brunohorta82** [comment]
i need use the apn "wm" and if i use "wm " the device can register on the network, you can fix this to accept only two chars?
