### ISSUE TITLE
cJSON 

### ISSUE THREAD

**Issue by niwantha33** [Ai-Thinker-Open/GPRS_C_SDK#336]
I tried to compile the demo "json" (https://raw.githubusercontent.com/Ai-Thinker-Open/GPRS_C_SDK/master/demo/json/src/demo_json.c) sample,  but the result was full of errors (please check below) . 

## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

Build host is LINUX

MAKE              init

MAKE              libs

MAKE              demo/json
CC                demo_json.c
AR                libjson_debug.a

LDGEN  by csdk    cust.ld
LD                json.elf
/home/niwantha/projects/GPRS_C_SDK/build/json/demo/json/lib/libjson_debug.a(demo_json.o): In function `STD_TestTask':
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:94: undefined reference to `cJSON_CreateObject'
value:0, p:ffffffff88240146, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:94: relocation truncated to fit: R_MIPS16_26 against `cJSON_CreateObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:102: undefined reference to `cJSON_CreateString'
value:0, p:ffffffff8824014e, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:102: relocation truncated to fit: R_MIPS16_26 against `cJSON_CreateString'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:102: undefined reference to `cJSON_AddItemToObject'
value:0, p:ffffffff88240158, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:102: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddItemToObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:102: undefined reference to `cJSON_CreateObject'
value:0, p:ffffffff8824015e, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:102: relocation truncated to fit: R_MIPS16_26 against `cJSON_CreateObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:103: undefined reference to `cJSON_AddItemToObject'
value:0, p:ffffffff8824016a, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:103: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddItemToObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:104: undefined reference to `cJSON_AddStringToObject'
value:0, p:ffffffff88240174, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:104: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddStringToObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:105: undefined reference to `cJSON_AddNumberToObject'
value:0, p:ffffffff88240180, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:105: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddNumberToObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:106: undefined reference to `cJSON_AddNumberToObject'
value:0, p:ffffffff8824018c, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:106: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddNumberToObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:107: undefined reference to `cJSON_AddFalseToObject'
value:0, p:ffffffff88240194, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:107: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddFalseToObject'
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:108: undefined reference to `cJSON_AddNumberToObject'
value:0, p:ffffffff882401a0, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:108: relocation truncated to fit: R_MIPS16_26 against `cJSON_AddNumberToObject'
/home/niwantha/projects/GPRS_C_SDK/build/json/demo/json/lib/libjson_debug.a(demo_json.o): In function `print_preallocated':
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:108: undefined reference to `cJSON_Print'
value:0, p:ffffffff882401a6, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:108: additional relocation overflows omitted from the output
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:45: undefined reference to `Assert'
value:0, p:ffffffff882401d4, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:54: undefined reference to `Assert'
value:0, p:ffffffff88240200, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:58: undefined reference to `cJSON_PrintPreallocated'
value:0, p:ffffffff8824020c, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:75: undefined reference to `cJSON_PrintPreallocated'
value:0, p:ffffffff88240262, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/build/json/demo/json/lib/libjson_debug.a(demo_json.o): In function `STD_TestTask':
/home/niwantha/projects/GPRS_C_SDK/demo/json/src/demo_json.c:87: undefined reference to `cJSON_Delete'
value:0, p:ffffffff882402ca, addend:0, symbol:0
/home/niwantha/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:722: recipe for target '/home/niwantha/projects/GPRS_C_SDK/build/json//json.elf' failed
make[2]: *** [/home/niwantha/projects/GPRS_C_SDK/build/json//json.elf] Error 1
/home/niwantha/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:718: recipe for target '/home/niwantha/projects/GPRS_C_SDK/build/json//json.srec' failed
make[1]: *** [/home/niwantha/projects/GPRS_C_SDK/build/json//json.srec] Error 2
/home/niwantha/projects/GPRS_C_SDK/platform/compilation/cust_rules.mk:371: recipe for target 'lod' failed
make: *** [lod] Error 2
}

---

**Comment by niwantha33** [comment]
problem was solved by using new SDK

**Comment by JazminFerre** [comment]
Hi, where can i get the new SDK?
Thanksss!!!
