### ISSUE TITLE
gps is fixed

### ISSUE THREAD

**Issue by CallaDai** [Ai-Thinker-Open/GPRS_C_SDK#351]
run the demo/gps file, it shows me "GPS fix mode:1, BDS fix mode:1, fix quality:0, satellites tracked:0, gps sates total:0, is fixed:no fix, coordinate:WGS84, Latitude:22.607593, Longitude:113.830580, unit:degree,altitude:0.000000" . But my location is not here. how to change it? for the fixed, how can I change to mode 2?

**Comment by Duh3c** [comment]
Fix mode:1 means there is no fix. You just have to wait for a fix. Sometimes 13min+. I suggest you go somewhere outside and just wait.

**Comment by CallaDai** [comment]
> Fix mode:1 means there is no fix. You just have to wait for a fix. Sometimes 13min+. I suggest you go somewhere outside and just wait.

Done! Many thanks!
