### ISSUE TITLE
I wonder this module can steal my data?

### ISSUE THREAD

**Issue by txhai** [Ai-Thinker-Open/GPRS_C_SDK#372]
Hello, I am trying to work with the SDK but I cannot find the implementation of API functions. I think if there are hidden codes that send the GPS data to a certain server? 

How do I know this module does not do that?

Thanks.

**Comment by pulkin** [comment]
There is no way to do that. GPS, however, is a separate chip via UART so it is easy to take control of this kind of communication. There is base station tracking which you cannot take control of.

**Comment by txhai** [comment]
Thank you for your answer @pulkin, I really appreciate it. But can you describe in more details? I am new to IoT and cannot understand all of your words. I think there are instructions that `Start GPS Chip -> Get the data -> Start GPRS -> Send via TCP`.

**Comment by pulkin** [comment]
GPS tracking example: https://github.com/Ai-Thinker-Open/GPRS_C_SDK/tree/master/demo/gps_tracker/src

**Comment by txhai** [comment]
Edited: I mean the SDK contains hidden instructions would do steal the data, like your file attached above

**Comment by pulkin** [comment]
Yes, this is possible.

**Comment by txhai** [comment]
Thank you! This is a great module but give the doubt.
