### ISSUE TITLE
GPIO interrupt mode problem

### ISSUE THREAD

**Issue by hakraf** [Ai-Thinker-Open/GPRS_C_SDK#374]
Hello,
I have a problem with using gpio pin as interrupter, i tried pins 2 to 7 and they works great, but other pins not working.
is interrupt mode just works with pins 2 to 7 ? or works with all gpio pins ?

**Comment by peterjschulze** [comment]
Based on the documentation and our testing only GPIO 0 to 7 operate as
interrupts.


Peter

**Comment by hakraf** [comment]
Yes, that's what I find too, thank you for your answer.
