### ISSUE TITLE
GPS demo Longitude:0

### ISSUE THREAD

**Issue by punee995** [Ai-Thinker-Open/GPRS_C_SDK#39]
![gps](https://user-images.githubusercontent.com/7541915/34530279-a23fc3a6-f0d4-11e7-803c-e9e8828d538e.png)

In GPS Demo shows Longitude:0.

**Comment by punee995** [comment]
i've made change in gps_parse.h on line 127 and  191.
changed `if ( ( *temp >= 0x31 ) && ( *temp <= 0x39 ) )` to this `if ( *temp != 0 )` and it works.

**Comment by Neutree** [comment]
that is:
change
```
if ( ( *temp >= 0x31 ) && ( *temp <= 0x39 ) )
```
to
```
if ( ( *temp >= 0x30 ) && ( *temp <= 0x39 ) )
```
