### ISSUE TITLE
Links expired

### ISSUE THREAD

**Issue by emeric0101** [Ai-Thinker-Open/GPRS_C_SDK#412]
Hello

All links in https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/installation.html 
for downloading CSDK42 are expired, can you help me please ?

**Comment by zkemble** [comment]
Hey emeric, I've uploaded CSDK42 here along with the latest SDK stuff since the last official release https://github.com/zkemble/GPRS_C_SDK/releases/tag/v2.129

**Comment by emeric0101** [comment]
@zkemble you saved my day !

Thank you

**Comment by gumby0q** [comment]
there is linux version:
`https://github.com/pulkin/csdtk42-linux`

**Comment by Benedito821** [comment]
> Hey emeric, I've uploaded CSDK42 here along with the latest SDK stuff since the last official release https://github.com/zkemble/GPRS_C_SDK/releases/tag/v2.129

@zkemble  is there the windows version of CSDK42?
