### ISSUE TITLE
Link for download CSDTK42.7z not working

### ISSUE THREAD

**Issue by qwertydzen** [Ai-Thinker-Open/GPRS_C_SDK#413]
## 1. SDK version（SDK 版本）

{

Latest

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

I have tried to download CSDTK4.2 as written there https://ai-thinker-open.github.io/GPRS_C_SDK_DOC/en/c-sdk/installation.html

But not working filesharing links and direct link 

Download CSDTK4.2: baidu cloud,MEGA cloud，direct link

Please update readme 
Thank you!

}

---

**Comment by zkemble** [comment]
Check here! -> #412
