### ISSUE TITLE
will my new schema work?

### ISSUE THREAD

**Issue by pagman** [Ai-Thinker-Open/GPRS_C_SDK#438]
Hello, i have being playing for a while now with the a9g pudding board and now i want to make my own pcb design for a simple gps tracker (not led's, io etc), my plan is with the debug headers to upload my own firmware other than that it will be a simple pcb.  i am not planning on having usb connection, The module will be powered by an 18650 battery  

i would appriciate if you can give me your thoughts on my design and if you think it is gonna work.
i am sorry in advance because it is my first design schema so it might not look profetional at all

![a9gboardgit](https://user-images.githubusercontent.com/19304517/86100461-802b5780-bac1-11ea-819c-71a04932ce21.PNG)

**Comment by MakhmudSultonov** [comment]
![fix](https://user-images.githubusercontent.com/14884272/87247606-4ddd0b00-c46e-11ea-85c2-4bde12c90757.png)

**Comment by pagman** [comment]
thank you i have completely overlook the power key ! 
i am thinking to use a tantalum capacitor fot the 100uf  and a ceramic for the 100nf  for the decoupling you think they will be fine? Thank you

**Comment by zkemble** [comment]
R1 and R2 are not needed. The A9 can already read the battery voltage using PM_Voltage(). See this #421 about your decoupling, 100u might be ok since you're directly connected to a battery and not dealing with an SD card.

**Comment by pagman** [comment]
> R1 and R2 are not needed. The A9 can already read the battery voltage using PM_Voltage(). See this #421 about your decoupling, 100u might be ok since you're directly connected to a battery and not dealing with an SD card.

Thank you for the help! I thought I need the voltage devider even for using the PM_Voltage(), because I saw this on the schematic.
![IMG_20200714_131151](https://user-images.githubusercontent.com/19304517/87414091-dfb25880-c5d3-11ea-877d-29ab56a407f0.jpg)

**Comment by zkemble** [comment]
I'm not sure why they have it there, maybe it just makes it easier to test the external ADC stuff. This project of mine #396 can still read the supply voltage without it.

**Comment by pagman** [comment]
> I'm not sure why they have it there, maybe it just makes it easier to test the external ADC stuff. This project of mine #396 can still read the supply voltage without it.

thank you i really appriciate you help! i think my questions about the schematic are covered i am marking it as closed
