### ISSUE TITLE
下载调试都没问题，重新上电就报错是怎么回事？程序没有运行

### ISSUE THREAD

**Issue by zhaowenwin** [Ai-Thinker-Open/GPRS_C_SDK#44]
Detected XCPU in the GDB loop (0x9db00000), connect GDB debugger for more info.
Detected BCPU in the GDB loop (0x9db10000), connect GDB debugger for more info.

**Comment by Neutree** [comment]
程序死机，使用adb调试，或者检查是否有指针错误
