### ISSUE TITLE
CSDTK links not working (direct link, mega, baidu cloud)

### ISSUE THREAD

**Issue by ece-mohammad** [Ai-Thinker-Open/GPRS_C_SDK#454]
## 1. SDK version（SDK 版本）

{
CSDTK 4.2 ($Revision: 43828 $)
GPRS_C_SDK_V2108
}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
As the title says, the CSDTK4.2 links in github releases, and SDK documentation wiki are not working. The file is no-longer available.
}

---

**Comment by CouDeGras** [comment]
Same here pls resolve asap

**Comment by wzab** [comment]
I confirm. Tools are not available. I can't start working with the board :(

**Comment by nguyenvanduocit** [comment]
Anyone have downloaded the file?

**Comment by ZakKemble** [comment]
Check here! -> #412

**Comment by nguyenvanduocit** [comment]
@zkemble thanks

**Comment by ece-mohammad** [comment]
@zkemble Thanks

**Comment by nguyenvanduocit** [comment]
@ece-mohammad Why did you close the issue without fixing? Link to the fork does not fix. Or we need to move the issue to repo GPRS_C_SDK_DOC?
