### ISSUE TITLE
Toolchain CSDTK4.2 no longer available to download

### ISSUE THREAD

**Issue by HolgerFe** [Ai-Thinker-Open/GPRS_C_SDK#487]
Can you please re-upload the toolchain? 
It's no longer available on the mentioned sources:
baidu cloud
MEGA cloud
direct link

## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

}

---

**Comment by ZakKemble** [comment]
Check here! -> #412

**Comment by HolgerFe** [comment]
Thank you! :)
