### ISSUE TITLE
GPS demo always return the same latitude and longitude

### ISSUE THREAD

**Issue by MarcoAntonini** [Ai-Thinker-Open/GPRS_C_SDK#49]
The GPS demo code always returns the same latitude and longitude

<img width="1423" alt="schermata 2018-01-13 alle 17 54 02" src="https://user-images.githubusercontent.com/2572234/34908133-333851bc-f88b-11e7-87d3-fe85303b5348.png">

**Comment by Neutree** [comment]
just because your gps not fix
gps or bds fix should be 2(2D fix) or 3(3D fix) but not 1(no fix)
check your GPS antenna then put it outdoors

**Comment by MarcoAntonini** [comment]
i'm sorry, the problem was my rf cable. I've changed it, now I get the right values and a fixgps > 1.
