### ISSUE TITLE
Can't download CSDTK4.2 CoolWatcher

### ISSUE THREAD

**Issue by l-sannin** [Ai-Thinker-Open/GPRS_C_SDK#490]
Hello, i can't download the folder CSDTK4.2 and Icant find the coolwatcher to upload my code.

**Comment by pirj** [comment]
Check this https://github.com/Ai-Thinker-Open/GPRS_C_SDK/issues/412

**Comment by l-sannin** [comment]
Thanks a lot, so this means board discontinued?

**Comment by pirj** [comment]
I don't think so. I've recently purchases one.
However, it's a 2G board, and https://en.wikipedia.org/wiki/GSM#Discontinuation

The SDK hasn't seen updates for a couple of years now. It may be considered to be feature-complete, though.

**Comment by l-sannin** [comment]
Thank you very much for the information, now it is clear to me

**Comment by l-sannin** [comment]
Closed
