### ISSUE TITLE
a9g module wont start

### ISSUE THREAD

**Issue by JazminFerre** [Ai-Thinker-Open/GPRS_C_SDK#493]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

Hi!
I just buy my A9G module and when I tried to power on with USB 5V it doesnt work. I dont know how to fix it.
I measured the 5V and are ok.

}

---

**Comment by MbarkErras** [comment]
more details please? how do you know it doesn't start

**Comment by JazminFerre** [comment]
Hi thanks for the answer I fixed it by going back to firmware version 2018. I am quite new to this and don't understand many things.
Thanks again!!!!

**Comment by MbarkErras** [comment]
@JazminFerre good luck, feel free to reach out
