### ISSUE TITLE
A9G信息上传服务器

### ISSUE THREAD

**Issue by sqm289798469** [Ai-Thinker-Open/GPRS_C_SDK#5]
如何连接服务器的tcp地址及端口，把模块的GPS信息定时发送到服务器，这方面的源码可否提供

**Comment by Neutree** [comment]
TCP连接参见`demo/socket`例程
GPS参见demo/gps

**Comment by sqm289798469** [comment]
对代码这块不是很了解，可以直接拿demo来用吗

**Comment by Neutree** [comment]
你先看看视频看看文档看看代码。。。
