### ISSUE TITLE
请问可不可以直接在eclipse上开发呢？

### ISSUE THREAD

**Issue by HelloAnpengyu** [Ai-Thinker-Open/GPRS_C_SDK#50]
求大神出个eclipse配置教程。。

**Comment by Neutree** [comment]
emmmm  暂时没有计划弄eclipse

**Comment by HelloAnpengyu** [comment]
还有个问题请教大神，成功连接到服务器之后开始透传数据的时候，如果因为网络不稳定导致发送失败会不会有事件产生呢？

**Comment by Neutree** [comment]
有的，会产生socket error事件

**Comment by HelloAnpengyu** [comment]
太好了٩(•̤̀ᵕ•̤́๑)ᵒᵏ前天下的单，期待赶紧到手(●◡●)ﾉ
