### ISSUE TITLE
how to create task please explain help me?

### ISSUE THREAD

**Issue by Trion** [Ai-Thinker-Open/GPRS_C_SDK#530]
I created three task in main.c
this correct way ? 
please explain about that 
create task for multiple thread
mqtt connection 
httpconnection
uart communication 
#define MAIN_TASK_STACK_SIZE    (2048 * 2)
#define MAIN_TASK_PRIORITY      0
#define MAIN_TASK_NAME          "Main Test Task"

#define SECOND_TASK_STACK_SIZE    (2048 * 2)
#define SECOND_TASK_PRIORITY      1
#define SECOND_TASK_NAME          "MQTT Test Task"

#define HTTP_TASK_STACK_SIZE    (2048 *2)
#define HTTP_TASK_PRIORITY      2
#define HTTP_TASK_NAME          " HTTP Test Task"

## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

}

---

**Comment by islamAbdullah** [comment]
in the main function you need to call the OS_CreateTask() three times for the three tasks.

**Comment by Trion** [comment]
thanks for your help.
