### ISSUE TITLE
SDK可以提供FLASH读写操作吗？

### ISSUE THREAD

**Issue by helloccccccc** [Ai-Thinker-Open/GPRS_C_SDK#54]
如题，需要保存256B左右的数据，TF保存或外扩EEPROM均不太合适，能否提供API读写片上的FLASH？翻了demo，没发现在哪个文件下有相关读写说明。

**Comment by Neutree** [comment]
FS == file system,
使用文件系统即可，更方便，文件系统是在flash上，没有TF卡也可以用，有TF卡的话会自动挂载到`/t`目录下
