### ISSUE TITLE
cJSON依赖头文件

### ISSUE THREAD

**Issue by roamboy** [Ai-Thinker-Open/GPRS_C_SDK#56]
可否提供cJSON依赖的标准头文件
math.h, float.h, limits.h

**Comment by roamboy** [comment]
报个cJSON链接问题
/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/build/gw/gw/lib/libgw_debug.a(gw_main.o): In function `print_number':
/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/gw/src/utils/cJSON/cJSON.c:502: undefined reference to `sscanf'
value:0, p:ffffffff8824135c, addend:0, symbol:0
/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/gw/src/utils/cJSON/cJSON.c:502: relocation truncated to fit: R_MIPS16_26 against `sscanf'
/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/build/gw/gw/lib/libgw_debug.a(gw_main.o): In function `parse_number':
/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/gw/src/utils/cJSON/cJSON.c:316: undefined reference to `strtod'
value:0, p:ffffffff882416e2, addend:0, symbol:0
/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/gw/src/utils/cJSON/cJSON.c:316: relocation truncated to fit: R_MIPS16_26 against `strtod'
make[2]: *** [/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/build/gw//gw.elf] Error 1
make[1]: *** [/cygdrive/d/Workspace/Src/A9G/gprs_c_sdk/build/gw//gw.srec] Error 2

**Comment by punee995** [comment]
you can try **jsmn** lib which is minimalistic JSON parser in C.

**Comment by roamboy** [comment]
it's only parser, hope support cJSON

**Comment by Neutree** [comment]
cJSON was add to the lib with source code now
