### ISSUE TITLE
请问这是怎么回事

### ISSUE THREAD

**Issue by Destiny9701** [Ai-Thinker-Open/GPRS_C_SDK#57]
![image](https://user-images.githubusercontent.com/27015024/35180812-834b2ad2-fdf2-11e7-8f5b-151f1159e464.png)

**Comment by Destiny9701** [comment]
![image](https://user-images.githubusercontent.com/27015024/35180822-9ac791d2-fdf2-11e7-9cc9-639d8783bb0a.png)
命令出错

**Comment by Neutree** [comment]
解压好CSDTK3.8后，请不要使用记事本或者写字板编辑，
使用vscode ，notpad++，sublime text， atom等等这些编辑器都行

**Comment by Neutree** [comment]
cygwin的结束符是`<LF>`即`\n`，记事本会把它变成`<CR><LF>`，即`\r\n`，这样做是不对的

**Comment by Destiny9701** [comment]
@Neutree 我使用的是sublime text，这个有所了解

**Comment by Destiny9701** [comment]
![image](https://user-images.githubusercontent.com/27015024/35180949-9ca76af2-fdf4-11e7-8584-43d4a99704ac.png)
请问一下，那我重新下载再编辑？

**Comment by Destiny9701** [comment]
好的,谢谢了，有可能是我双击的时候用记事本打开过什么了，我把这些重装试下。

**Comment by Neutree** [comment]
把文件改成 <LF>换行就行了

**Comment by Neutree** [comment]
http://blog.csdn.net/marco_90/article/details/42004109

http://www.codes51.com/itwd/4395205.html

**Comment by Destiny9701** [comment]
好的，十分感谢解答，原来sublime text设置不对也会出现这样问题
