### ISSUE TITLE
SPI

### ISSUE THREAD

**Issue by ap10000** [Ai-Thinker-Open/GPRS_C_SDK#60]
请问SPI什么时候更新啊？

**Comment by Neutree** [comment]
本周

**Comment by Neutree** [comment]
代码已经更新，可以拉取尝试使用

https://github.com/Ai-Thinker-Open/GPRS_C_SDK/releases

**Comment by ap10000** [comment]
谢谢！

**Comment by MaBarakat** [comment]
@Neutree
 hi,你好
我想問的是在A9G模組中使用spi寫入快閃記憶體還是必須使用TF卡 ?
請幫忙並解答

I am asking about using spi to write on flash memory or must using TF card in A9G module ?
Please help and answer
