### ISSUE TITLE
关于开关机按键

### ISSUE THREAD

**Issue by Spring641** [Ai-Thinker-Open/GPRS_C_SDK#62]
请问我再A9G开发板上接电池，长按开机键可以开机，后面再长按开关机不能关机。目前是不支持关机么？

**Comment by Neutree** [comment]
关机请调用代码

**Comment by Spring641** [comment]
好的，明白你的意思。那这个长按关机键在哪里判断呢？那请问连接的GPIO是哪个呢？手册没有写，还有SDK要调用哪个函数才能关机呢？

**Comment by Neutree** [comment]
电源相关的接口参见`api_hal_pm.h`，看函数名你就知道是什么函数了。

识别长按关机键的话，后面我加一个关机键长按事件

**Comment by Spring641** [comment]
好的多谢

**Comment by Neutree** [comment]
加入了，现在power key 按下或者释放会有事件产生:https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/include/api_inc/api_event.h/#L12

**Comment by Spring641** [comment]
好的，多谢

**Comment by Neutree** [comment]
在demo pm中已经加入了例程

**Comment by Spring641** [comment]
收到！
