### ISSUE TITLE
MQTT SSL 在使用域名进行连接时死机

### ISSUE THREAD

**Issue by brainbush** [Ai-Thinker-Open/GPRS_C_SDK#67]
## 1. SDK version（SDK 版本）

{

1.504

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

![image](https://user-images.githubusercontent.com/2290026/35563517-da07700e-05f1-11e8-9409-2db563832f42.png)
连接配置中broker_hostname和MQTT_Connect中的broker_ip均为域名，在返回DNS结果后就进入死循环。
在broker ip中使用ip地址则不会出现这种问题，在之前的1.402的SDK中也不会出现这样的问题。

谢谢。
}

---

**Comment by Neutree** [comment]
可以暂时先调用dns解析，获得ip后再传入mqtt

**Comment by brainbush** [comment]
嗯嗯，谢了……
