### ISSUE TITLE
编译链接的时候报错

### ISSUE THREAD

**Issue by itolddd** [Ai-Thinker-Open/GPRS_C_SDK#73]
SDK版本是V1.406，我在app路径下加了个include文件夹，放自己的.h文件，在src里放了几个自己的.c，其他就是写了几个测试函数。编译的时候好像没有报错，但链接报错，请问这个是什么原因？新增文件还需要改哪里吗？

$ ./build.sh app
compile project app
compile path /cygdrive/E/AiThinker/Code/GPRS_C_SDK_V1.406/app

MAKE              init

MAKE              app

LDGEN  by csdk    cust.ld
LD                app.elf
ElfCombine        Elf binary & map file

GEN               stripped (rm syms) elf file app.elf
mips-elf-ld: /cygdrive/E/AiThinker/Code/GPRS_C_SDK_V1.406/hex/app/app.elf: access beyond end of merged section (-99877632)

CP                AUDIO CFP FILE......
AUDIO CFG         No audio cfp file
SREC              app.srec for flash/romulator

LODTOBIN  e:\AiThinker\Code\GPRS_C_SDK_V1.406\hex\app\app_flash.lod
LODTOBIN          Sucessful
LODCOMBINE        Combine user lod with Platform lod
LODCOMBINE        Combine sucessful

=== Build Time: 32s at 2018-02-01 15:54:17 ===
grep: ./build//.map: No such file or directory
grep: ./build//.map: No such file or directory
grep: ./build//.map: No such file or directory
grep: ./build//.map: No such file or directory
grep: ./build//.map: No such file or directory
./build.sh: line 155: -: syntax error: operand expected (error token is "-")
awk: BEGIN{printf "%.2f%\n",(/0x00100000)*100}
awk:                          ^ unterminated regexp
awk: cmd. line:1: BEGIN{printf "%.2f%\n",(/0x00100000)*100}
awk: cmd. line:1:                                          ^ unexpected newline or end of string
./build.sh: line 158: -: syntax error: operand expected (error token is "-")
./build.sh: line 159: -+: syntax error: operand expected (error token is "+")
awk: BEGIN{printf "%.2f%\n",(/0x00100000)*100}
awk:                          ^ unterminated regexp
awk: cmd. line:1: BEGIN{printf "%.2f%\n",(/0x00100000)*100}
awk: cmd. line:1:                                          ^ unexpected newline or end of string
ROM total: 0x00100000(1048576) Bytes, used: Bytes ()
RAM total: 0x00100000(1048576) Bytes, used: Bytes ()

**Comment by Neutree** [comment]
请更新到最新版本，第一个抱错用build.sh clean all可以解决，后面的一堆错是因为脚本没找到文件 更新到最新的版本就可以了
