### ISSUE TITLE
Socket_TcpipWrite的返回值的含义？

### ISSUE THREAD

**Issue by HelloAnpengyu** [Ai-Thinker-Open/GPRS_C_SDK#74]
## 1. SDK version（SDK 版本）

{

V1.506
A9G

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

请问Socket_TcpipWrite的返回值是什么？据我观察发送成功的时候返回值不一样。

}

---

**Comment by Neutree** [comment]
写长度

**Comment by will88china** [comment]
Socket_TcpipWrite只能用一次吗？为什么第二次就无法写入呢？
