### ISSUE TITLE
无法下载程序

### ISSUE THREAD

**Issue by alu-cqx** [Ai-Thinker-Open/GPRS_C_SDK#76]
我的A9G按教程里的做然后无法下载到板子里。我确定USBTTL是正常的。我已经看了10几次下载的常见错误了，视频也看了两三次了。我板子上的接法就是HST-Rx接Tx HST-TX接RX，还有什么地方要注意的吗？
我注意到我下载的包里面的host_8955_flsh_spi32m_ramrun是大约15KB对吗？

**Comment by alu-cqx** [comment]
问题已处理

**Comment by CallaDai** [comment]
额，还有视频？地址是哪里？我下载了无数遍，一直报告错误，链接不上。
