### ISSUE TITLE
下载完后出现这个

### ISSUE THREAD

**Issue by alu-cqx** [Ai-Thinker-Open/GPRS_C_SDK#77]
## 1. SDK version（SDK 版本）

{

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

 `waitCommandResult': Event aknowledging end of command never received! (FastPf::FlashCommandUnacknowledged)

}

---

**Comment by Neutree** [comment]
看看这里 #9
