### ISSUE TITLE
Trace(1,"%.*s",strlen(str), str); Not Working!

### ISSUE THREAD

**Issue by punee995** [Ai-Thinker-Open/GPRS_C_SDK#78]
## 1. SDK version（SDK 版本）

{
 v1.406
}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

**Not Working!**

`Trace(1,"%.*s",strlen(str), str); `

`sprintf(str2, "%.*s", strlen(str), str);`

}

---

**Comment by punee995** [comment]
also `char *strndup(const char *str, size_t size);` not supported
please add full support for **string.h**

**Comment by Neutree** [comment]
* RE(Regular Expression) is not supported in sprintf or sscanf

* `strndup` not belongs to  standard of string.h, and it used malloc internally may make someone do some memory leak error, so you can add it by yourself, and you can event custom your `sprintf` or `sscanf` in `stdio.h`
