### ISSUE TITLE
hello what's the meaning of "Timeout while trying to access the resource" in i2c

### ISSUE THREAD

**Issue by jackccchen1** [Ai-Thinker-Open/GPRS_C_SDK#81]
## 1. SDK version（SDK 版本）

{

1.506

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

}

---

**Comment by jackccchen1** [comment]
how can I　handle　ｔｈｅ　ｅｒｒｏｒ

**Comment by Neutree** [comment]
超时
