### ISSUE TITLE
关于IO口电压问题

### ISSUE THREAD

**Issue by Joker-Zhao** [Ai-Thinker-Open/GPRS_C_SDK#84]
typedef enum{
    POWER_TYPE_VPAD = 0,            // GPIO0  ~ GPIO7  and GPIO25 ~ GPIO36    2.8V   //always on
    POWER_TYPE_MMC,                 // GPIO8  ~ GPIO13                        1.9V
    POWER_TYPE_LCD,                 // GPIO14 ~ GPIO18                        1.9V
    POWER_TYPE_CAM,                 // GPIO19 ~ GPIO24                        1.9V
    POWER_TYPE_MAX
}Power_Type_t;
请问一下，IO口注释后面的电压是不是表明这些IO口的输出高电平电压仅仅支持2.8v或1.9
v？

**Comment by punee995** [comment]
i can't get your question?? (language problem).

but i think **GPIO0  ~ GPIO7**  and **GPIO25 ~ GPIO36** has logic level of **2.8v** also use as **UARTx** & **HST_UART**,
and **GPIO8~GPIO24** has logic level of **1.9v** also can be used in **MMC**,**Camera** and **LCD**  interface.

user manual for A9g : http://wiki.ai-thinker.com/_media/a6_a9_a9g_gprs_user_manual.pdf
