### ISSUE TITLE
如何设置板子上的时钟？

### ISSUE THREAD

**Issue by xiaojianbj** [Ai-Thinker-Open/GPRS_C_SDK#91]
现在获取到的时间和实际的时间不匹配，有什么接口可以设置吗？或者有哪个接口可以同步时钟？

**Comment by vencol** [comment]
TIME_SetRtcTime

**Comment by Destiny9264** [comment]
![image](https://user-images.githubusercontent.com/37217642/37253659-aef72542-256f-11e8-9a11-3305af2de44b.png)
我写的程序好像是必须API_EVENT_ID_SYSTEM_READY之后调用TIME_SetRtcTime可以设置。现在没问题了

**Comment by Neutree** [comment]
[demo/time](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/time/src/demo_time.c)
