### ISSUE TITLE
GPS no Time zone data

### ISSUE THREAD

**Issue by ittchmh** [Ai-Thinker-Open/GPRS_C_SDK#92]
## 1. SDK version（SDK 版本）

{
Ai Thinker Co.LTD
A9/A9G

V01.05.20171014RC
}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
GPS Fix success but no $GPZDA data available 

GPS Fix Data:
$GPGGA,111509.000,5001.0000,N,03621.0000,E,2,4,1.86,195.9,M,16.8,M,,*51
$GPGSA,A,3,17,28,05,07,,,,,,,,,2.08,1.86,0.92*02
$GPGSV,3,1,12,28,77,081,16,13,67,277,16,30,47,092,,15,36,303,16*77
$GPGSV,3,2,12,07,22,096,21,17,21,158,31,20,19,283,,08,16,037,*73
$GPGSV,3,3,12,11,15,080,17,05,12,226,28,19,04,172,,46,,,*40
$GPRMC,111509.000,A,5001.0000,N,03621.0000,E,2.230,197.74,090318,,,D*59
$GPVTG,197.74,T,,M,2.230,N,4.132,K,D*33

}

How to get $GPZDA or enable output of such data?
---

**Comment by Neutree** [comment]
you can get timezone info from gprs:[demo/time](https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/demo/time/src/demo_time.c)
