### ISSUE TITLE
gps Speed course问题

### ISSUE THREAD

**Issue by Destiny9264** [Ai-Thinker-Open/GPRS_C_SDK#93]
## 1. SDK version（SDK 版本）

{

**V1.05**

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

1. 

Knot_speed为负数，course也是负数，speed为0这个按照那个closed issue里改下就可以吗？

2. 
希望官方多增加必要注释，有些变量不知道什么意思

}

---

**Comment by Destiny9264** [comment]
希望增加解析卫星数

**Comment by Neutree** [comment]
demo只是提供一个不够完善的解析代码作为参考，每个人的写法不一样，GPS输出是标准的NMEA格式，只是对字符的一系列处理而已，以后有时间可以考虑完善一下demo的解析函数
