### ISSUE TITLE
二次开发程序下载到2%断开

### ISSUE THREAD

**Issue by tcp01** [Ai-Thinker-Open/GPRS_C_SDK#94]
## 1. SDK version（SDK 版本）

{

GPRS_C_SDK_V1505

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{

    USB供电，每次下载到2%断开。

}

---

![a9g_errordownload](https://user-images.githubusercontent.com/37220574/37217365-45b5c71e-23f8-11e8-856c-2d8a20e5a92d.png)
![a9g_errordownload_serial](https://user-images.githubusercontent.com/37220574/37217467-8c148c40-23f8-11e8-87fc-84f8827331d9.png)

**Comment by punee995** [comment]
**Try this ....**

https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/doc/download_debug_tool_zh-cn.md#coolwatcher%E6%97%A0%E6%B3%95%E4%B8%8B%E8%BD%BD

**Comment by Neutree** [comment]
重新连接试试，可以开始下载应该连接没有问题的，确认一下是不是电源提供能力不够
