### ISSUE TITLE
build.sh编译程序的时候出现一个弹窗显示的标题和内容是：ZbxLodToBin 参数错误！

### ISSUE THREAD

**Issue by Vandoul** [Ai-Thinker-Open/GPRS_C_SDK#96]
## 1. SDK version（SDK 版本）

{

V1505

}

---

## 2. In what kind of operation problems appear, and how to reproduce the problem ?（什么样的操作步骤问题会出现，是否是稳定复现，如何复现问题？）

{
每次都会出现这个问题，编译demo里面的例程都会有这个问题。不影响编译结果，就是每次会报错有点烦人。

}

---

**Comment by punee995** [comment]
please give image for more info!

**Comment by jackccchen1** [comment]
你的文件路径不能有‘-’之类字符
