### ISSUE TITLE
V505编译之后显示RAM/ROM缺少文件夹

### ISSUE THREAD

**Issue by chenfuvip** [Ai-Thinker-Open/GPRS_C_SDK#99]
LODTOBIN  r:\A9G\GPRS_C_SDK_V1505\hex\gps\gps_flash.lod
LODTOBIN          Sucessful
LODCOMBINE        Combine user lod with Platform lod
LODCOMBINE        Combine sucessful

=== Build Time: 27s at 2018-03-19 10:54:57 ===
/usr/bin/sh: /bin/awk: No such file or directory
/usr/bin/sh: /bin/awk: No such file or directory
/usr/bin/sh: /bin/awk: No such file or directory
/usr/bin/sh: /bin/awk: No such file or directory
/usr/bin/sh: /bin/awk: No such file or directory
/usr/bin/sh: /bin/awk: No such file or directory
/usr/bin/sh: /bin/awk: No such file or directory
./build.sh: line 214: -: syntax error: operand expected (error token is "-")
/usr/bin/sh: /bin/awk: No such file or directory
./build.sh: line 217: -: syntax error: operand expected (error token is "-")
./build.sh: line 218: -+: syntax error: operand expected (error token is "+")
/usr/bin/sh: /bin/awk: No such file or directory
ROM total: (0) Bytes, used: Bytes ()
RAM total: (0) Bytes, used: Bytes ()

**Comment by Neutree** [comment]
应该是脚本哪里识别到文件夹相关的问题了，发的这个log看不出问题
